// src/components/page/public/home/RulesCard.tsx
"use client";

import Link from "next/link";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

export default function RulesCard() {
  return (
    <Card className="border-white/10 bg-[#253649]/70 backdrop-blur">
      <CardHeader className="space-y-2">
        <CardTitle className="text-xl text-zinc-100">Rules</CardTitle>
        <p className="text-sm text-zinc-200/85">
          Keep rankings meaningful. Logs must reflect real gameplay.
        </p>
      </CardHeader>

      <CardContent className="space-y-5">
        <div className="rounded-xl border border-white/10 bg-[#1F2B3A]/55 p-4">
          <p className="text-sm font-medium text-zinc-100">Core rules</p>

          <ul className="mt-3 space-y-2 text-sm text-zinc-200/90">
            <li className="flex gap-3">
              <span className="mt-2 h-1.5 w-1.5 rounded-full bg-emerald-400" />
              No knowingly bugged/exploitable abilities to gain unfair advantage.
            </li>
            <li className="flex gap-3">
              <span className="mt-2 h-1.5 w-1.5 rounded-full bg-emerald-400" />
              Do not toggle <span className="text-zinc-100">/combatlog</span> mid-encounter.
            </li>
            <li className="flex gap-3">
              <span className="mt-2 h-1.5 w-1.5 rounded-full bg-emerald-400" />
              No edited logs or “half parses” intended to skew leaderboards.
            </li>
            <li className="flex gap-3">
              <span className="mt-2 h-1.5 w-1.5 rounded-full bg-emerald-400" />
              One public “master” upload per unique session/raid ID.
            </li>
          </ul>
        </div>

        <div className="rounded-xl border border-white/10 bg-white/5 p-4">
          <p className="text-sm font-medium text-zinc-100">Anti Cheat </p>
          <p className="mt-2 text-sm leading-relaxed text-zinc-200/85">
            I have made an anti cheat system to detect some common forms of cheating or log
            manipulation. If your uploads never shows up in your sessions list, it's probably because
            something was detected. If you think a mistake has been made, please reach out on Discord
            to discuss. 
            <br /> <br />
            What doeas it do ?
            <br /> <br />
            - Detects edited logs (logs that have been modified after being generated by the game)
            <br />
            - Detects double burst or some other bug with the Wild Storm
            <br />
            - Detects some forms of impossible healing or damage values
          </p>
        </div>

        <div className="flex flex-wrap gap-3">
          <Button
            asChild
            variant="outline"
            className="border-white/15 bg-white/5 text-zinc-100 hover:bg-white/10"
          >
            <Link href="/rules">Read full rules</Link>
          </Button>

          <Button asChild className="bg-emerald-500 text-white hover:bg-emerald-400">
            <Link href="/account">Accept & upload</Link>
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
