// src/components/page/public/rules/AntiCheatCard.tsx
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export default function AntiCheatCard() {
  return (
    <Card className="border-white/10 bg-[#253649]/70 backdrop-blur">
      <CardHeader className="space-y-2">
        <CardTitle className="text-xl text-zinc-100">Anti-cheat</CardTitle>
        <p className="text-sm text-zinc-200/85">
          Automated checks detect common forms of log manipulation and suspicious patterns.
        </p>
      </CardHeader>

      <CardContent className="space-y-4">
        <div className="rounded-xl border border-white/10 bg-[#1F2B3A]/55 p-4 text-sm text-zinc-200/90 leading-relaxed">
          <p>
            If an upload never shows up in your session list, it’s likely because something was
            detected. If you believe it’s a false positive, reach out on Discord.
          </p>

          <div className="mt-4 rounded-lg border border-white/10 bg-white/5 p-3">
            <p className="text-sm font-medium text-zinc-100">What it checks (examples)</p>
            <ul className="mt-2 space-y-2 text-sm text-zinc-200/90">
              <li className="flex gap-3">
                <span className="mt-2 h-1.5 w-1.5 rounded-full bg-emerald-400" />
                Edited logs (files modified after being generated by the game).
              </li>
              <li className="flex gap-3">
                <span className="mt-2 h-1.5 w-1.5 rounded-full bg-emerald-400" />
                “Double burst” or bug patterns with Wild Storm.
              </li>
              <li className="flex gap-3">
                <span className="mt-2 h-1.5 w-1.5 rounded-full bg-emerald-400" />
                Some impossible damage/healing values.
              </li>
            </ul>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
