// src/lib/ability-icons.ts

export type AbilityIconRule = {
  key: string;
  aliases: string[];
};

export const ABILITY_ICON_RULES: AbilityIconRule[] = [
  { key: "1h_mace_049", aliases: ["Unknown"] },
  { key: "2h_axe_036_a", aliases: ["Coup brutal"] },
  { key: "2h_axe_043_a", aliases: ["Frappe brutale", "Brutal Strike"] },
  { key: "2h_polearm_019_a", aliases: ["Unknown"] },
  { key: "2h_staff_078a", aliases: ["Rift Spear"] },
  { key: "2h_sword_069a", aliases: ["Lame des Élus", "Blade of the Ascended"] },
  { key: "2h_sword_078_a", aliases: ["Bénédiction ultime", "Final Blessing"] },
  { key: "absolution_01_a", aliases: ["Absolution"] },
  { key: "absolution_01_b", aliases: ["Spirit Sight"] },
  { key: "active_treatment", aliases: ["Active Treatment"] },
  { key: "adrenaline_overdrive", aliases: ["Adrenaline Overdrive"] },
  { key: "adrenaline_shot", aliases: ["Injection d'adrénaline", "Adrenaline Shot"] },
  { key: "aegis_of_advocacy", aliases: ["Égide de défense", "Aegis of Advocacy"] },
  { key: "aegis_of_sanctuary", aliases: ["Égide de sanctuaire", "Aegis of Sanctuary"] },
  { key: "alchemy2n", aliases: ["Flasque de siphonnage d'impuretés", "Impurity Siphoning Flask"] },
  { key: "ameliorate", aliases: ["Bonifier", "Ameliorate"] },
  { key: "anthem_of_competence", aliases: ["Hymne de compétence", "Anthem of Competence"] },
  { key: "anthem_of_defiance", aliases: ["Unknown"] },
  { key: "anthem_of_fervor", aliases: ["Hymne de ferveur", "Anthem of Fervor"] },
  { key: "anthem_of_glory", aliases: ["Hymne de gloire", "Anthem of Glory"] },
  { key: "arcane_ward", aliases: ["Arcane Ward"] },
  { key: "arcaneshield2", aliases: ["Armure élémentaire", "Elemental Armor"] },
  { key: "arcaneshield3", aliases: ["Bouclier de glace", "Geyser", "Ice Shield"] },
  { key: "arcaneshield4", aliases: ["Armure de Pyromancien", "Pyromancer's Armor"] },
  { key: "arcaneshield4aa", aliases: ["Fontis d'oblitération", "Font of Obliteration"] },
  { key: "archane_projection", aliases: ["Arcane Projection"] },
  { key: "archon-earthen_barrage", aliases: ["Barrage de Terre", "Earthen Barrage"] },
  { key: "archon-earthen_barrage_b", aliases: ["Salve vorpale", "Vorpal Salvo"] },
  { key: "archon-earthen_barrage_e", aliases: ["Pointe tectonique", "Tectonic Spike"] },
  { key: "archon_crumbling_resistance_01", aliases: ["Crumbling Resistance"] },
  { key: "archon_crumbling_resistance_01_e", aliases: ["Rage de la Tempête", "Storm Rage"] },
  { key: "archon_point_to_point", aliases: ["D'un point à l'autre", "Point to Point"] },
  { key: "archon_rock_slide", aliases: ["Appel de pierre", "Call of Stone"] },
  { key: "archon_rock_slide_a", aliases: ["Séisme", "Granite Salvo", "Earthquake"] },
  { key: "ardent_doctrine_01", aliases: ["Intention brûlante", "Burning Purpose"] },
  { key: "ardent_doctrine_01_a", aliases: ["Engagement du guérisseur", "Healer's Covenant"] },
  { key: "arkanxshield1", aliases: ["Cœur de la mer gelée", "Heart of the Frozen Sea"] },
  { key: "arm_wavea", aliases: ["Perspicacité", "Insight"] },
  { key: "assassin_leaping_plunge", aliases: ["Leaping Plunge"] },
  { key: "assassin_thread_of_death_b", aliases: ["Fil de la Mort", "Colère de l'esprit", "Spirit's Wrath"] },
  { key: "auto_attack_2", aliases: ["Bioclasme/Fouet d'air", "Bind Life/Air Lash"] },
  { key: "awareness_01", aliases: ["Appel de l'observateur", "On en remet une couche", "Piling On"] },
  { key: "backstab", aliases: ["Poignard dans le dos", "Backstab"] },
  { key: "backstab_a", aliases: ["Ultime instant", "Final Moment"] },
  { key: "baneful_touch_01", aliases: ["Corpse Talon"] },
  { key: "baneful_touch_01_b", aliases: ["Scission primitive", "Primal Sunder"] },
  { key: "barbedtrap1", aliases: ["Éruption de Vie", "Poussée de vie", "Eruption of Life"] },
  { key: "bard_harmonic_distortion", aliases: ["Distorsion harmonique", "Harmonic Distortion"] },
  { key: "bard_harmonic_distortion_a", aliases: ["Soins intensifs", "Intensive Care"] },
  { key: "bard_orchestra_of_the_planes", aliases: ["Orchestra of the Planes"] },
  { key: "bard_verse_of_agony", aliases: ["Couplet d'agonie"] },
  { key: "beastmaster-lesser_corporeal_manifestation_a", aliases: ["Invocation de Smilodon primitif inférieur"] },
  { key: "beastmaster_beast_whisperer_01", aliases: ["Influence apaisante", "Calming Influence"] },
  { key: "beastmaster_bond_of_might_a", aliases: ["Bond of Power"] },
  { key: "beastmaster_comp_intervention", aliases: ["Bond of Shelter"] },
  { key: "beastmaster_enraged_companion_01_a", aliases: ["Instincts voraces", "Enragement", "Enrage"] },
  { key: "beastmaster_enraged_companion_aura_01_a", aliases: ["Appel de barbarie", "Sauvagerie primitive", "Call of Savagery", "Primal Savagery"] },
  { key: "beastmaster_kinship_01", aliases: ["Appel d'affinité", "Call of Kinship"] },
  { key: "beastmaster_protective_companion_01", aliases: ["Invocation de Smilodon primitif supérieur"] },
  { key: "beastmaster_shared_bonds", aliases: ["Congère"] },
  { key: "beastmaster_shared_bonds_a", aliases: ["En eaux profondes", "Open Water"] },
  { key: "beastmaster_shared_bonds_b", aliases: ["Unknown"] },
  { key: "beastmaster_shared_bonds_c", aliases: ["Fae Mimicry"] },
  { key: "berserk1a", aliases: ["Battlefield Intimidation"] },
  { key: "berserk1b", aliases: ["Ordre du sergent"] },
  { key: "berserk3", aliases: ["Allure de soldat"] },
  { key: "berserk4", aliases: ["Regard paralysant", "Paralyzing Glare"] },
  { key: "berserk4c", aliases: ["Fureur du Titan", "Titan's Fury"] },
  { key: "berserk4d", aliases: ["Tonification", "Invigorate"] },
  { key: "binding_of_affliction_01_a", aliases: ["Décret de mort", "Lien d'affliction", "Death's Edict", "Binding of Affliction"] },
  { key: "binding_of_authority_01", aliases: ["Trait de châtiment", "Bolt of Retribution"] },
  { key: "binding_of_death_01", aliases: ["Exhumation", "Courant viral", "Exhume"] },
  { key: "biofeedback", aliases: ["Causal Treatment"] },
  { key: "biting_wind", aliases: ["Biting Wind"] },
  { key: "blade_tempo", aliases: ["Blade Tempo"] },
  { key: "bladedancer_hundred_blades_c", aliases: ["Hundred Blades"] },
  { key: "blazeofglory1a", aliases: ["Command to Attack"] },
  { key: "blazeofglory3", aliases: ["Command to Stand Ground"] },
  { key: "bleeding", aliases: ["Balayage sauvage"] },
  { key: "bleeding_aa", aliases: ["Unknown"] },
  { key: "blessing_of_the_flames", aliases: ["Flamme de Vie", "Flame of Life"] },
  { key: "blessing_of_the_flames_a", aliases: ["Bouclier de volonté", "Déchaînement de fureur", "Shield of Will"] },
  { key: "blindinglight1", aliases: ["Examen spirituel"] },
  { key: "bloodfire1", aliases: ["Vague de chaleur", "Heat Wave"] },
  { key: "bolt_of_radiance_01", aliases: ["Healing Torrent"] },
  { key: "bolt_of_radiance_01_a", aliases: ["Bolt of Radiance"] },
  { key: "bomb_annihilation", aliases: ["Bombe collante d'annihilation", "Annihilation Sticky Bomb"] },
  { key: "bomb_fragment", aliases: ["Bombe collante à fragmentation", "Fragmentation Sticky Bomb"] },
  { key: "bomb_fragment_a", aliases: ["Burst Synergy"] },
  { key: "bomb_specialist", aliases: ["Grande explosion", "Cauterizing Wave", "Grand Explosion"] },
  { key: "bomb_time", aliases: ["Bombe à retardement", "Time Bomb"] },
  { key: "boon_of_resurgence_b", aliases: ["Bénédiction de renaissance", "Boon of Resurgence"] },
  { key: "boon_of_vitality_b", aliases: ["Bénédiction de vitalité", "Boon of Vitality"] },
  { key: "burning", aliases: ["Vacillement", "Flicker"] },
  { key: "cabalist-binding_waters_a", aliases: ["Chemins sinueux", "Winding Paths"] },
  { key: "cabalist_sigil_of_ravaging_a", aliases: ["Malédiction de la discorde", "Curse of Discord"] },
  { key: "cadence_a", aliases: ["Cadence"] },
  { key: "campfire1", aliases: ["Araser", "Raze"] },
  { key: "carpet_bombing_a", aliases: ["Montée de fureur", "Building Fury"] },
  { key: "castigate", aliases: ["Dam", "Castigate"] },
  { key: "castigation1a", aliases: ["Défense de cendres", "Ashen Defense"] },
  { key: "castigation1b", aliases: ["Armure de traîtrise", "Armor of Treachery"] },
  { key: "castigation1c", aliases: ["Armure de dévotion", "Armor of Devotion"] },
  { key: "castigation3", aliases: ["Armure du réveil", "Défense du bouclier", "Armor of Awakening"] },
  { key: "casual_treatment", aliases: ["Tir temporal", "Temporal Shot"] },
  { key: "cauterize1", aliases: ["Calcination", "Char"] },
  { key: "cauterizea", aliases: ["Destin en sursis", "Delayed Fate"] },
  { key: "cautious_stalker", aliases: ["Impunité", "Impunity"] },
  { key: "cavalier_01", aliases: ["Doctrine glorieuse", "Doctrine of Glory"] },
  { key: "censure_01", aliases: ["Backhand"] },
  { key: "censure_01a", aliases: ["Frappe essentielle", "Essence Strike"] },
  { key: "chainlighting1", aliases: ["Éclair fourchu", "Forked Lightning"] },
  { key: "chainlighting2", aliases: ["Batterie de ranimation"] },
  { key: "chainlighting5a", aliases: ["Explosion d'orage"] },
  { key: "champion-bull_rush", aliases: ["Charge du taureau", "Bull Rush"] },
  { key: "champion-destroyers_bearing", aliases: ["Allure de destructeur", "Destroyer's Bearing"] },
  { key: "champion_mark_of_convergence", aliases: ["Assaut assassin", "Killer Assault"] },
  { key: "champion_mark_of_convergence_a", aliases: ["Mark of Exclusion"] },
  { key: "champion_second_wind_a", aliases: ["Chant résurrectionnel"] },
  { key: "champion_second_wind_e", aliases: ["Fontis de barbarie", "Font of Savagery"] },
  { key: "champion_thunderous_strike", aliases: ["Frappe assourdissante", "Dégelée de froid", "Cold Snap"] },
  { key: "champion_thunderous_strike_a", aliases: ["Lacération fourvoyante", "Distracting Slash"] },
  { key: "channelhealth2", aliases: ["Unknown"] },
  { key: "channelhealth3", aliases: ["Unknown"] },
  { key: "channelhealth4", aliases: ["Mortalité", "Chant méditatif", "Mortality"] },
  { key: "charge1", aliases: ["Frappe ravageuse", "Ravaging Strike"] },
  { key: "charge2", aliases: ["Attaque complexe", "Compound Attack"] },
  { key: "charge3", aliases: ["Mur d'acier", "Flash of Steel"] },
  { key: "charge3a", aliases: ["Frappe punitive", "Punishing Blow"] },
  { key: "charge4z", aliases: ["Frappe puissante", "Power Strike"] },
  { key: "charge_blast", aliases: ["Unknown"] },
  { key: "charge_concussion", aliases: ["Grenade déflagrante", "Flashbang"] },
  { key: "charge_shrapnel_1", aliases: ["Voie de la roche", "Path of Stone"] },
  { key: "charge_splinter", aliases: ["Bombe collante à dispersion", "Scatter Sticky Bomb"] },
  { key: "chloromancer-natural_conversion", aliases: ["Conversion naturelle", "Natural Conversion"] },
  { key: "chloromancer_entropic_veil_01", aliases: ["Entropic Veil"] },
  { key: "chloromancer_entropic_veil_01_a", aliases: ["Unknown"] },
  { key: "chloromancer_void_life_01", aliases: ["Unknown"] },
  { key: "chloromancer_void_life_01_a", aliases: ["Couver/Dénaturer", "Nurture"] },
  { key: "cleave1", aliases: ["Cascade ascendante", "Rising Waterfall"] },
  { key: "close_combat", aliases: ["Maîtrise du combat à distance", "Ranged Combat Mastery"] },
  { key: "coalesceheat1", aliases: ["Explosion de cendres", "Cinder Burst"] },
  { key: "coda_of_cowardice", aliases: ["Coda de lâcheté", "Coda of Cowardice"] },
  { key: "coda_of_distress", aliases: ["Coda de détresse", "Coda of Distress"] },
  { key: "coda_of_distress_a", aliases: ["Coda du péril", "Coda of Jeopardy"] },
  { key: "coda_of_fury", aliases: ["Coda de fureur", "Coda of Fury", "Chains of Death"] },
  { key: "coda_of_fury_a", aliases: ["Reprise", "Chaînes de Vie", "Chains of Life"] },
  { key: "coda_of_restoration_a", aliases: ["Coda de restauration", "Coda of Restoration"] },
  { key: "coda_of_restoration_b", aliases: ["Flux d'essence", "Essence Flow"] },
  { key: "coda_of_wrath_a", aliases: ["Coda de colère", "Coda of Wrath"] },
  { key: "combat_culmination", aliases: ["Rage de la bête", "Open the Stream", "Rage of the Beast"] },
  { key: "combat_pose1", aliases: ["Danse mortelle", "Deadly Dance"] },
  { key: "combat_pose1_a", aliases: ["Combat Preparation"] },
  { key: "combat_survival_a", aliases: ["Tape d'essence", "Essence Tap"] },
  { key: "concussion_01", aliases: ["Oblitération illimitée"] },
  { key: "concussion_01_b", aliases: ["Pierre de pillage", "Apathie forcée", "Pillaging Stone", "Forced Apathy"] },
  { key: "concussive_blast_01", aliases: ["Explosion à secousse", "Concussive Blast"] },
  { key: "conflagration1", aliases: ["Tempête de feu", "Fire Storm"] },
  { key: "conflagration2", aliases: ["Charbons ardents", "Burning Ground"] },
  { key: "conflagration3", aliases: ["Incendium", "Conflagrate"] },
  { key: "conflict_avoidance", aliases: ["Évitement de conflit", "Conflict Avoidance"] },
  { key: "confound1", aliases: ["Appréhension", "Spasm"] },
  { key: "confound2", aliases: ["Bewilder"] },
  { key: "continuous_treatment", aliases: ["Continuous Treatment"] },
  { key: "conviction_01", aliases: ["Cavalier"] },
  { key: "corrective_measures", aliases: ["Mesures de correction", "Corrective Measures"] },
  { key: "corroded_defense", aliases: ["Défense corrodée", "Corroded Defense"] },
  { key: "counteract", aliases: ["Contrebalance", "N'y pensez plus !", "Counteract", "Brush it Off!"] },
  { key: "creeping_death_01", aliases: ["Unknown"] },
  { key: "creeping_death_01_b", aliases: ["Ombre du trépas", "Shadow of Demise"] },
  { key: "cripplingshot1", aliases: ["Fourche", "Fork"] },
  { key: "critical2a", aliases: ["Frappe de précision", "Flamespear"] },
  { key: "critical4", aliases: ["Déchirure de la chair", "Flesh Rip"] },
  { key: "criticalstrike1", aliases: ["A Quick Death"] },
  { key: "criticalsweep1b", aliases: ["Balayage"] },
  { key: "criticalsweep3c", aliases: ["Fureur de lame", "Bladefury"] },
  { key: "crystallize", aliases: ["Cristallisation", "Crystallize"] },
  { key: "curse_of_consumption", aliases: ["Curse of Consumption"] },
  { key: "curse_of_frailty", aliases: ["Curse of Frailty"] },
  { key: "curse_of_solitude", aliases: ["Confluence", "Malédiction de la solitude", "Conflux", "Curse of Solitude"] },
  { key: "dancing_steel", aliases: ["Danse de l'acier", "Dancing Steel"] },
  { key: "dark_containment_01", aliases: ["Lien maléfique", "Distorsion ombrale", "Confinement obscur", "Essence Link", "Dark Containment"] },
  { key: "dark_harbor", aliases: ["Impulsion choquante", "Voie de la foudre", "Path of Lightning"] },
  { key: "dark_malady_01", aliases: ["Dark Malady"] },
  { key: "dark_waters", aliases: ["Infection"] },
  { key: "dark_waters_a", aliases: ["Eau sombre", "Dark Water"] },
  { key: "darkball1", aliases: ["Armure d'Anathema"] },
  { key: "darkball2", aliases: ["Armure obscure", "Dark Armor"] },
  { key: "darkball2z", aliases: ["Contact obscur", "Dark Touch"] },
  { key: "darkball4", aliases: ["Barrage du Néant"] },
  { key: "darkbolt2", aliases: ["Unknown"] },
  { key: "darkbolt3", aliases: ["Contact de l'ombre", "Shadow's Touch"] },
  { key: "darkbolt5", aliases: ["Absorption impie", "Draining Bolt"] },
  { key: "debilitating_poison_01_a", aliases: ["Dard affaiblissant", "Debilitating Dart"] },
  { key: "debilitating_poison_01_b", aliases: ["Poison absorbant", "Leeching Poison"] },
  { key: "defensive_favor", aliases: ["Faveur défensive", "Defensive Favor"] },
  { key: "defensivestrike1", aliases: ["Precept of Refuge"] },
  { key: "defensivestrike3", aliases: ["Dégagement", "Disengage"] },
  { key: "defer_death", aliases: ["Allure de la faucheuse", "Defer Death"] },
  { key: "defiler_beacon_of_despair", aliases: ["Fétiche du tourment"] },
  { key: "defiler_bond_of_corruption", aliases: ["Lien de corruption", "Bond of Corruption"] },
  { key: "defiler_bond_of_pain_cc", aliases: ["Lien de souffrance", "Bond of Pain"] },
  { key: "defiler_bond_of_torment", aliases: ["Lien de tourment", "Bond of Torment"] },
  { key: "defiler_chimeras_gift_w", aliases: ["Unknown"] },
  { key: "defiler_deaths_embrace_a", aliases: ["Essence de la Faucheuse"] },
  { key: "defiler_empowered_affliction_a", aliases: ["Bouclier du vent du nord"] },
  { key: "defiler_empowered_affliction_cc", aliases: ["Aversion"] },
  { key: "defiler_feedback", aliases: ["Force furieuse", "Furious Might"] },
  { key: "defiler_foul_growth_b", aliases: ["Champ corrompu", "Corrupted Field"] },
  { key: "defiler_ghastly_restoration_b", aliases: ["Affliction miséreuse", "Miserly Affliction"] },
  { key: "defiler_ghastly_restoration_g", aliases: ["Unknown"] },
  { key: "defiler_grief_blight", aliases: ["Corruption de cupidité", "Greed's Corruption"] },
  { key: "defiler_grief_blight_a", aliases: ["Avarice agressive", "Aggressive Avarice"] },
  { key: "defiler_hideous_reconstruction", aliases: ["Fragments des bas-fonds", "Underworld Shards"] },
  { key: "defiler_husk_of_indifference_a", aliases: ["Enveloppe d'indifférence", "Husk of Indifference"] },
  { key: "defiler_jealous_intervention_a", aliases: ["Intervention jalouse", "Jealous Intervention"] },
  { key: "defiler_link_of_agony", aliases: ["Ombre de terreur", "Shadow of Dread"] },
  { key: "defiler_link_of_agony_a", aliases: ["Appel de la Rage", "Call of Rage"] },
  { key: "defiler_link_of_misery_a", aliases: ["Lien de la misère", "Link of Misery"] },
  { key: "defiler_loathsome_restoration_d", aliases: ["Pandémie", "Pandemic"] },
  { key: "defiler_loathsome_restoration_g", aliases: ["Agonie dévorante", "Consuming Agony"] },
  { key: "defiler_marrow_harvest", aliases: ["Récolte de moelle", "Marrow Harvest"] },
  { key: "defiler_pain_transmission_b", aliases: ["Pain Transmission"] },
  { key: "defiler_rage_blight", aliases: ["Extracteur de Rage", "Rage Extraction"] },
  { key: "defiler_rage_blight_a", aliases: ["Infection furieuse", "Furious Infestation"] },
  { key: "defiler_rage_blight_b", aliases: ["Rage explosive", "Explosive Rage"] },
  { key: "defiler_sanguine_desecration", aliases: ["Profanation somatique", "Somatic Desecration"] },
  { key: "defiler_siphon_vitality_a", aliases: ["Siphon Vitality"] },
  { key: "defiler_unholy_nexus_a", aliases: ["Nexus impie"] },
  { key: "defiler_unstable_transformation_a", aliases: ["Unknown"] },
  { key: "deflect1c", aliases: ["Brûlure", "Burn"] },
  { key: "deflect2", aliases: ["Ordre réfléchissant", "Reflective Command"] },
  { key: "deflect2a", aliases: ["Fontis de rétribution", "Font of Retaliation"] },
  { key: "deflection1a", aliases: ["Dualisme", "Dualism"] },
  { key: "deflection2b", aliases: ["Marche du vent"] },
  { key: "deflection3", aliases: ["Unknown"] },
  { key: "deflection4c", aliases: ["Garde d'acier", "Inspirations profondes", "Guarded Steel", "Deep Breaths"] },
  { key: "deflection4cc", aliases: ["Double Coup"] },
  { key: "deliverance", aliases: ["Affranchissement", "Deliverance"] },
  { key: "demolition_specialist", aliases: ["Avatar des Flammes", "Avatar of Flame"] },
  { key: "detonate", aliases: ["Détonation", "Detonate"] },
  { key: "detonate_a", aliases: ["Fusillade"] },
  { key: "detoxification", aliases: ["Désintoxication", "Detoxification"] },
  { key: "devouring_mist", aliases: ["Allure de mastodonte", "Juggernaut's Bearing"] },
  { key: "devouring_mist_a", aliases: ["Préservation éternelle", "Eternal Preservation"] },
  { key: "devouring_mist_b", aliases: ["Transcendâme", "Oversoul"] },
  { key: "devout_conviction_01", aliases: ["Unknown"] },
  { key: "dichotomy_of_pain", aliases: ["Dichotomie de la douleur", "Dichotomy of Pain"] },
  { key: "diffuse_01", aliases: ["Garde du corps", "Diffuse"] },
  { key: "dirtytricks1a", aliases: ["Persister", "Voies redessinées", "Paths Rewritten"] },
  { key: "dirtytricks3", aliases: ["Contamination", "Instigation de masse", "Contaminate", "Mass Instigate"] },
  { key: "disabling1a", aliases: ["Frappe aiguisée", "Keen Strike"] },
  { key: "disabling2", aliases: ["Frappe planaire", "Planar Strike"] },
  { key: "disabling3a", aliases: ["Frappe cruelle"] },
  { key: "disabling4", aliases: ["Frappe au poignet", "Désarmer", "Disassemble"] },
  { key: "discerning_wave", aliases: ["Discerning Wave"] },
  { key: "discombobulate1", aliases: ["Destruction de sort"] },
  { key: "discombobulate2", aliases: ["Espoir perdu", "Lost Hope"] },
  { key: "discombobulate2b", aliases: ["Prédestination", "Predestination"] },
  { key: "discombobulate3a", aliases: ["Champ de lave", "Lava Field"] },
  { key: "distorted_shadows", aliases: ["Brèche de l'Ombre", "Shadow Breach"] },
  { key: "distorted_shadows_b", aliases: ["(EN) Malevolent Bolt", "Malevolent Bolt"] },
  { key: "divert_rage_01", aliases: ["Diversion", "Divert Rage"] },
  { key: "doctrine_of_authority_01_a", aliases: ["Impulsion chargée", "Healing Effusion", "Charged Pulse"] },
  { key: "doctrine_of_bliss_01", aliases: ["Bassin de restauration"] },
  { key: "doctrine_of_bliss_01_b", aliases: ["Doctrine de béatitude", "Doctrine of Bliss"] },
  { key: "doctrine_of_bliss_01_c", aliases: ["Abondance de vie", "Flammes purificatrices", "Fullness of Life", "Cleansing Flames", "Judgment"] },
  { key: "doctrine_of_faithful_01", aliases: ["Égide vivante", "Living Aegis", "Light's Protection"] },
  { key: "doctrine_of_loyalty_01_a", aliases: ["Assurance complète", "Allure de domination", "Dominating Bearing"] },
  { key: "doctrine_of_virtue_01", aliases: ["Privilège judiciaire", "Judicial Privilege"] },
  { key: "dominator-mass_exhaustion_b", aliases: ["Épuisement de masse", "Oblitération condensée", "Mass Exhaustion", "Condensed Obliteration"] },
  { key: "dominator-split_personality", aliases: ["Unknown"] },
  { key: "dominator_draining_presence_01", aliases: ["Corruption entretenue"] },
  { key: "dominator_draining_presence_01_b", aliases: ["Unknown"] },
  { key: "dominator_lighting_wall_a", aliases: ["Mur de foudre", "Explosion électrique", "Lightning Wall", "Electricity Blast"] },
  { key: "dominator_nyxs_orb_b", aliases: ["Orbe de Nyx", "Bouclier électromagnétique", "Nyx's Orb", "Electromagnetic Shield"] },
  { key: "dominator_pain_armor_a", aliases: ["Armure de souffrance", "Pain Armor"] },
  { key: "double_cross_01", aliases: ["Frappe rapide", "En chasse", "Frappe relevée", "On the Hunt", "Seasoned Strike", "Swift Strike"] },
  { key: "double_shot_01", aliases: ["Unknown"] },
  { key: "drainlife1", aliases: ["Absorption vitale", "Life Leech"] },
  { key: "drainlife3", aliases: ["Blessures ouvertes", "Neddra's Grasp"] },
  { key: "druid-bombard_b", aliases: ["Broyage sismique", "Seismic Smash"] },
  { key: "druid-grim_silence", aliases: ["Grim Silence"] },
  { key: "druid-hidden_path", aliases: ["Hors des sentiers battus", "Ruine", "Hidden Path"] },
  { key: "druid-stone_strike_b", aliases: ["Éboulement de pierres", "Rockslide"] },
  { key: "druid-strength_of_the_fae", aliases: ["Force des Fées"] },
  { key: "druid-summon_faerie", aliases: ["Fée guérisseuse"] },
  { key: "druid-summon_greater_faerie", aliases: ["Guérisseuse féérique majeure"] },
  { key: "druid-summon_satyr", aliases: ["Unknown"] },
  { key: "druid_greater_faerie_seer_b", aliases: ["Unknown"] },
  { key: "druid_summon_greater_satyr", aliases: ["Unknown"] },
  { key: "druid_summon_satyr_a", aliases: ["Unknown"] },
  { key: "dusk_to_dawn_01", aliases: ["Étreinte du vide", "Grasping Void"] },
  { key: "dusk_to_dawn_01_a", aliases: ["Acquittement", "Du crépuscule à l'aube", "Acquittal", "Dusk to Dawn"] },
  { key: "earthfall", aliases: ["Coulée de Terre", "Earthfall"] },
  { key: "ebon_fury_01", aliases: ["Négation", "Avatar de la Faille", "Fureur noire", "Pas de témoins", "Deny", "Avatar of the Rift", "Ebon Fury", "No Witnesses"] },
  { key: "ebon_terror_01", aliases: ["Ebon Terror"] },
  { key: "elemental_bolt1a", aliases: ["Trait incandescent", "Searing Bolt"] },
  { key: "elementalist_elemental_burst_a", aliases: ["Elemental Burst"] },
  { key: "elementalist_prismatic_armor", aliases: ["Armure prismatique", "Prismatic Armor"] },
  { key: "elementalist_prismatic_armor_a", aliases: ["Barrière de cristal", "Crystal Barrier"] },
  { key: "elementalist_prismatic_valley", aliases: ["Prismatic Volley"] },
  { key: "elementalres2b", aliases: ["Éléments intensifiés", "Intensify Elements"] },
  { key: "elementalward2a", aliases: ["Mur du Néant"] },
  { key: "elemres4", aliases: ["Flux statique", "Static Flux", "Ragestorm"] },
  { key: "elemres4b", aliases: ["Déchaînement de l'oubli"] },
  { key: "elemresist1", aliases: ["Elemental Forces"] },
  { key: "emblem_of_alacrity_01", aliases: ["Purification", "Cleanse"] },
  { key: "emblem_of_alacrity_02", aliases: ["Passé réécrit", "Rewritten Past"] },
  { key: "emblem_of_alactricy", aliases: ["Emblème de célérité", "Emblem of Alacrity"] },
  { key: "emergency_response", aliases: ["Intervention d'urgence", "Emergency Response"] },
  { key: "enchant1", aliases: ["Rupture élémentaire", "Elemental Rupture"] },
  { key: "enchanting_material_23", aliases: ["Rune d'inhibition", "Rune of Inhibition"] },
  { key: "energy_overload1", aliases: ["Tempête vivante", "Living Storm"] },
  { key: "energybeam1", aliases: ["Trait de flamme", "Explosion de furie", "Flame Bolt", "Fury Blast"] },
  { key: "energybeam2a", aliases: ["Unknown"] },
  { key: "energyburst3f", aliases: ["Entraves orageuses"] },
  { key: "energyburst5", aliases: ["Explosion aérienne", "Dispersion féerique", "Airburst", "Fae Dispersion"] },
  { key: "enflamed_rejuvenationa", aliases: ["Destin violent"] },
  { key: "ensnare1", aliases: ["Liens brûlants", "Burning Bonds"] },
  { key: "entropy_embrace", aliases: ["Destin lié", "Bound Fate"] },
  { key: "escape_artist_01", aliases: ["Artiste de l'évasion", "Escape Artist"] },
  { key: "escape_artist_01_b", aliases: ["Courroux du faucon", "Hawk's Wrath"] },
  { key: "even_justice_01", aliases: ["Justice équitable", "Even Justice"] },
  { key: "excommunicate", aliases: ["Excommunication", "Domination de lumière", "Excommunicate", "Light's Domination"] },
  { key: "exorcize1", aliases: ["Bénédiction du Capitaine", "Bosun's Blessing"] },
  { key: "exorcize2", aliases: ["Cercle de l'oubli", "Circle of Oblivion"] },
  { key: "expectant_treatment", aliases: ["Expectant Treatment"] },
  { key: "explosive_infestation_01_a", aliases: ["Poussière persistante", "Lingering Dust"] },
  { key: "exposeweak1b", aliases: ["Empalement", "Allure de tueur", "Impale"] },
  { key: "exposeweakness1", aliases: ["Mark of Inevitability"] },
  { key: "exposeweakness2a", aliases: ["Piqûre"] },
  { key: "exposeweakness4", aliases: ["Expose Weakness"] },
  { key: "extraordinary_care", aliases: ["Extraordinary Care"] },
  { key: "eye_of_the_storm", aliases: ["Œil de la Tempête", "Force tempétueuse", "Brouillard roulant", "Eye of the Storm", "Gale Force", "Rolling Fog"] },
  { key: "faithful_doctrine_01_a", aliases: ["Mandat du juste"] },
  { key: "fanaticism", aliases: ["Flamboiement cérébral", "Fanatisme", "Cerebral Flare", "Fanaticism"] },
  { key: "fanfare_of_power", aliases: ["Fanfare de puissance", "Fanfare of Power"] },
  { key: "fanfare_of_vigor", aliases: ["Fanfare de vigueur", "Fanfare of Vigor"] },
  { key: "fanfare_of_vigor_1", aliases: ["Cultiver", "Cultivate"] },
  { key: "fast_relief", aliases: ["Prompt soulagement", "Fast Relief"] },
  { key: "fatique", aliases: ["Pestilence"] },
  { key: "favor_of_the_current", aliases: ["Faveur du courant", "Abjuration transcendante", "Favor of the Current"] },
  { key: "fiery_chains_01_a", aliases: ["Chaînes ardentes", "Fiery Chains"] },
  { key: "fiery_spike_01", aliases: ["Fiery Spike"] },
  { key: "fiery_spike_01a", aliases: ["Pilum de lave", "Lava Lance"] },
  { key: "finalstrike2", aliases: ["Frappe intrépide", "Dauntless Strike", "Mark of Extermination"] },
  { key: "finalstrike3", aliases: ["Peur", "Fear"] },
  { key: "finalstrike3a", aliases: ["Peur de masse", "Mass Fear"] },
  { key: "fire_and_forget", aliases: ["Étouffement", "Deaden"] },
  { key: "fire_death_attunement_01", aliases: ["Bouclier dévorant", "Devouring Shield"] },
  { key: "fireball", aliases: ["Boule de feu", "Fireball"] },
  { key: "first_aid", aliases: ["Premiers secours", "First Aid"] },
  { key: "flame_speaker1", aliases: ["Rugissement primitif", "Primal Roar"] },
  { key: "flame_speaker1a", aliases: ["Protection de fortune", "Fortune Protection"] },
  { key: "flame_speaker_a", aliases: ["Healing Breath"] },
  { key: "flame_thrust_01", aliases: ["Flame Thrust"] },
  { key: "flame_thrust_01_a", aliases: ["Unknown"] },
  { key: "flash1", aliases: ["Rupture", "Propagation de flamboiement", "Flashover"] },
  { key: "flashback", aliases: ["Armure de tempête", "Storm Armor"] },
  { key: "flashback_a", aliases: ["Flash-back", "Flashback"] },
  { key: "fleeting_instincts_01", aliases: ["Rapid Summon"] },
  { key: "fleeting_instincts_01_a", aliases: ["Au pas de course", "On the Double"] },
  { key: "fleeting_instincts_02_b", aliases: ["Instincts fugitifs", "Fleeting Instincts"] },
  { key: "flesh_rot_01", aliases: ["Grave Rot"] },
  { key: "flesh_rot_01_b", aliases: ["Gangrène", "Flesh Rot"] },
  { key: "foul_play_01", aliases: ["Instigation", "Instigate"] },
  { key: "foul_play_02", aliases: ["Foul Play"] },
  { key: "frost_hammer1", aliases: ["Coup écrasant", "Crushing Blow"] },
  { key: "frosted_shield", aliases: ["Rime"] },
  { key: "frosted_ward", aliases: ["Frosted Ward"] },
  { key: "frostkeeper_earthen_barrier", aliases: ["Barrière terrestre", "Earthen Barrier"] },
  { key: "frostkeeper_earthmending", aliases: ["Force naturelle", "Guérison de la Terre", "Natural Force", "Earthmending"] },
  { key: "frostkeeper_frigid_embrace", aliases: ["Étreinte frigorifiante", "Frigid Embrace"] },
  { key: "frostkeeper_frostkeepers_armor", aliases: ["Armure du Gardegivre", "Frostkeeper's Armor"] },
  { key: "frostkeeper_frozen_wind", aliases: ["Frozen Wind"] },
  { key: "frostkeeper_infuse_magic", aliases: ["Infusion de magie", "Infuse Magic"] },
  { key: "galvanic_strike", aliases: ["Frappe galvanique", "Galvanic Strike"] },
  { key: "generic_ability_002", aliases: ["Frappe du serpent"] },
  { key: "generic_ability_004", aliases: ["Cunning Ruse"] },
  { key: "generic_ability_007", aliases: ["Frappe du titan"] },
  { key: "generic_ability_010", aliases: ["Estimations ésotériques", "Esoteric Estimations"] },
  { key: "generic_ability_010_a", aliases: ["Nécrofaction", "Necrotize"] },
  { key: "generic_ability_011", aliases: ["Esprit de la nature", "Peace of the Forest", "Lifebound Veil"] },
  { key: "generic_ability_013", aliases: ["Décret de lumière", "Hammer of Duty", "Light's Decree"] },
  { key: "generic_ability_015_a", aliases: ["Assassinat", "Assassinate"] },
  { key: "generic_ability_015_z", aliases: ["Lames balayantes", "Frappe faucheuse", "Sweeping Blades", "Scything Strike"] },
  { key: "generic_ability_016", aliases: ["Rune de retour", "Bouclier de l'Élu", "Rune of Return"] },
  { key: "generic_ability_018", aliases: ["Bénédiction de guérisseur", "Healer's Blessing"] },
  { key: "generic_ability_020", aliases: ["Death's Door", "Inspiration of Battle"] },
  { key: "generic_ability_021", aliases: ["Frappe perturbatrice", "Disruptive Strike"] },
  { key: "generic_ability_022", aliases: ["Faveur aérienne", "Aerial Boon"] },
  { key: "generic_ability_024_a", aliases: ["Intention", "Purpose"] },
  { key: "generic_ability_025", aliases: ["Cyclone", "Élémentaire d'Air majeur", "Frappes électrifiées", "Allonge pestiférée", "Electrified Strikes", "Plagued Reach"] },
  { key: "generic_ability_025_a", aliases: ["Avatar du Vent", "Avatar of Wind"] },
  { key: "generic_ability_025_c", aliases: ["Renforcement d'Âme", "Empower Soul"] },
  { key: "generic_ability_026_a", aliases: ["Diagnostic précis", "Energized Vitality", "Precise Diagnosis"] },
  { key: "generic_ability_027", aliases: ["Atrophie", "Atrophy"] },
  { key: "generic_ability_029", aliases: ["Emblème de glace", "Emblem of Ice"] },
  { key: "generic_ability_031", aliases: ["Rift Storm"] },
  { key: "generic_ability_031_2", aliases: ["Fast Summon"] },
  { key: "goo7b", aliases: ["Unknown"] },
  { key: "grim_blade_01", aliases: ["Into the Breach"] },
  { key: "group_assistance", aliases: ["Group Assistance"] },
  { key: "group_therapy", aliases: ["Thérapie de groupe", "Group Therapy"] },
  { key: "growing_energy_02", aliases: ["Fragments d'âme", "Soul Fragments"] },
  { key: "guardian_phase", aliases: ["Guardian Phase"] },
  { key: "hammer_of_virtue_01", aliases: ["Marteau de la foi", "Égide de lumière", "Hammer of Faith", "Aegis of the Light"] },
  { key: "hamstring2", aliases: ["Proie acculée", "Cornered Prey"] },
  { key: "harbinger_binding_fetters", aliases: ["Entraves éblouissantes", "Glaring Fetters"] },
  { key: "harbinger_blade_rush", aliases: ["Lame fiévreuse", "Blade Rush"] },
  { key: "harbinger_blademark", aliases: ["Blademark"] },
  { key: "harbinger_blademark_a", aliases: ["Dual Pulse"] },
  { key: "harbinger_blazing_light", aliases: ["Blazing Light"] },
  { key: "harbinger_charged_blade", aliases: ["Lame chargée", "Chute céleste", "Charged Blade"] },
  { key: "harbinger_conditioned_response_a", aliases: ["Conditioned Response"] },
  { key: "harbinger_disabling_shock_a", aliases: ["Choc neutralisant", "Explosion offensive", "Disabling Shock"] },
  { key: "harbinger_eldritch_armor", aliases: ["Armure eldritch", "Eldritch Armor"] },
  { key: "harbinger_empyrean_ascension_e", aliases: ["Ascension empyréenne", "Empyrean Ascension"] },
  { key: "harbinger_energy_beam", aliases: ["Double impulsion", "Double Pulse"] },
  { key: "harbinger_energy_beam_a", aliases: ["Sirocco", "Scirocco"] },
  { key: "harbinger_essence_of_wind_a", aliases: ["Essence du vent", "Essence of Wind"] },
  { key: "harbinger_essence_of_wind_b", aliases: ["Bourrasque", "Squall"] },
  { key: "harbinger_introspection", aliases: ["Introspection"] },
  { key: "harbinger_lighting_blade", aliases: ["Lame foudroyante", "Lightning Blade"] },
  { key: "harbinger_lighting_blade_a", aliases: ["Lames d'ébène", "Ebon Blades"] },
  { key: "harbinger_lucent_slash", aliases: ["Lucent Slash"] },
  { key: "harbinger_luminous_weapon", aliases: ["Bénédiction lumineuse", "Luminous Blessing"] },
  { key: "harbinger_luminous_weapon_c", aliases: ["Arme lumineuse", "Luminous Weapon"] },
  { key: "harbinger_phantom_blades", aliases: ["Lames de la destinée", "Charge foudroyante", "Fated Blades", "Lightning Charge"] },
  { key: "harbinger_phantom_blades2_a", aliases: ["Lames fantômes", "Phantom Blades"] },
  { key: "harbinger_phantom_blades2_b", aliases: ["Colère des Plans"] },
  { key: "harbinger_phase_step_a", aliases: ["Marche tellurique", "Phase Step", "Earthwalk"] },
  { key: "harbinger_piercing_beam", aliases: ["Piercing Beam"] },
  { key: "harbinger_planar_retreat", aliases: ["Unknown"] },
  { key: "harbinger_planar_retreat_b", aliases: ["Rafale amère", "Bitter Gust"] },
  { key: "harbinger_planar_retreat_f", aliases: ["Vent changeant", "Shifting Wind"] },
  { key: "harbinger_planar_retreat_z", aliases: ["Empoigner l'horizon", "Compte à rebours final", "Grasping the Horizon", "Final Countdown"] },
  { key: "harbinger_planar_shield", aliases: ["Bouclier planaire"] },
  { key: "harbinger_reapers_blade", aliases: ["Lame de la Faucheuse"] },
  { key: "harbinger_rending_slash", aliases: ["Entaille déchirante"] },
  { key: "harbinger_rending_slash_a", aliases: ["Frappe glaciale", "Glacial Strike"] },
  { key: "harbinger_storm_fury_a", aliases: ["Fureur de tempête", "Evasive Redirection"] },
  { key: "harbinger_storm_fury_b", aliases: ["Vent flagellant", "Lashing Wind"] },
  { key: "harbinger_storm_fury_e", aliases: ["Divergence"] },
  { key: "harbinger_storm_nova_a", aliases: ["Œil du cyclone", "Mousson", "Perfect Storm", "Monsoon"] },
  { key: "harbinger_storm_nova_c", aliases: ["Explosion de désorientation", "Disorienting Blast"] },
  { key: "harbinger_storm_shroud_z", aliases: ["Stabilité basse", "Low Stability"] },
  { key: "harbinger_storm_slash", aliases: ["Unknown"] },
  { key: "harbinger_tempest_wind_a", aliases: ["Unknown"] },
  { key: "harbinger_tempest_winds", aliases: ["Ouragan", "Hurricane"] },
  { key: "harbinger_vengeful_shock_a", aliases: ["Choc vengeur"] },
  { key: "harbinger_vengeful_shock_b", aliases: ["Emblème de douleur", "Emblem of Pain"] },
  { key: "harbinger_vorpal_slash", aliases: ["Unknown"] },
  { key: "hardened_stalker", aliases: ["Armure tempétueuse", "Concentration martiale", "Tempest Armor", "Combat Focus"] },
  { key: "hasted_time", aliases: ["Influence traîtresse"] },
  { key: "hasted_time_a", aliases: ["Mass Betrayal", "Sigil of Catastrophe"] },
  { key: "headshot1b", aliases: ["Deadeye Shot"] },
  { key: "headshot2", aliases: ["Dans le mille", "Bull's Eye"] },
  { key: "headshot3", aliases: ["Head Shot"] },
  { key: "heal1", aliases: ["Purification", "Remèdes naturels", "Natural Remedies"] },
  { key: "heal2", aliases: ["Invocation cruciale", "Crucial Invocation"] },
  { key: "heal2z", aliases: ["Invocation de soins", "Healing Invocation"] },
  { key: "heal3", aliases: ["Communion de soins", "Healing Communion"] },
  { key: "healed", aliases: ["Unknown"] },
  { key: "healing_flame", aliases: ["Unknown"] },
  { key: "healing_flare2", aliases: ["Flamboiement de soins", "Déformation primitive", "Healing Flare", "Primal Warp"] },
  { key: "healing_flare_a", aliases: ["Lumière revigorante", "Radical Coalescence", "Empowering Light"] },
  { key: "healing_flare_b", aliases: ["Unknown"] },
  { key: "healthchannel1b", aliases: ["Absorption de pouvoir", "Power Drain"] },
  { key: "healthchannel1g", aliases: ["Discipline de fer", "Fureur de la nature", "Harsh Discipline", "Nature's Fury"] },
  { key: "healthchannel2", aliases: ["Splendeur naturelle", "Natural Splendor"] },
  { key: "healthchannel3", aliases: ["Éléments stimulés", "Fusion de la chair", "Quicken Elements", "Fusion of Flesh"] },
  { key: "healthchannel3a", aliases: ["Canalisation des éléments", "Cascade", "Channel Elements"] },
  { key: "healthchannel3b", aliases: ["Unknown"] },
  { key: "heavybleeding", aliases: ["Saignée abondante", "Bloodletting"] },
  { key: "heavybleedinga", aliases: ["Déchire-esprit", "Rend Spirit"] },
  { key: "hellfire_blades_01", aliases: ["Coup décisif", "Lames des feux de l'enfer", "Hellfire Blades", "Decisive Strike"] },
  { key: "heroicsurge1", aliases: ["Esprit titanesque", "Titanic Spirit"] },
  { key: "heroicsurge1a", aliases: ["Reclaim Elements"] },
  { key: "hidden_veil_01", aliases: ["Blason d'entropie", "Hidden Veil", "Crest of Entropy"] },
  { key: "holysmite3", aliases: ["Force écrasante", "Crushing Force"] },
  { key: "holysmite4", aliases: ["Colère glacée", "Frozen Wrath"] },
  { key: "holystrength2", aliases: ["Ma Liberté de penser", "Liberty of Thought"] },
  { key: "holystrength3c", aliases: ["Détermination héroïque", "Heroic Resolve"] },
  { key: "holysweep1", aliases: ["Flamboiement d'arme"] },
  { key: "holysweep3a", aliases: ["Frappe brûlante", "Blazing Strike"] },
  { key: "holysweep3aa", aliases: ["Lame d'affinité élémentaire", "Blade of Elemental Affinity"] },
  { key: "holysweep3c", aliases: ["Lance de flammes", "Flame Lance"] },
  { key: "holysweep4d", aliases: ["Coup retentissant", "Resounding Blow"] },
  { key: "humbling_blow_01", aliases: ["Puissance flamboyante", "Flaring Power"] },
  { key: "icebolt1", aliases: ["Glaçon", "Icicle"] },
  { key: "icebolt2", aliases: ["Éruption glacée", "Icy Blast"] },
  { key: "icebolt3", aliases: ["Déluge explosif", "Hail Blast"] },
  { key: "icebolt4a", aliases: ["Destruction de givre", "Shatterfrost"] },
  { key: "icestorm-light", aliases: ["Glacial Mark"] },
  { key: "icestormdark", aliases: ["Orage de grêle", "Hailstorm"] },
  { key: "icestormdark_a", aliases: ["Fragments glacés", "Icy Shards"] },
  { key: "icy_cascade", aliases: ["Volée de grêle", "Cascade glaciale", "Barrière de givre", "Hail Volley", "Icy Cascade", "Frost Barrier"] },
  { key: "icy_heart1", aliases: ["Glace éternelle", "Ageless Ice"] },
  { key: "icy_heart2", aliases: ["Gel cardiaque", "Heart Freeze"] },
  { key: "immunization", aliases: ["Détoxification massive", "Mass Detox"] },
  { key: "impede1a", aliases: ["Tir d'arcane", "Arcane Shot"] },
  { key: "incapacitate_01", aliases: ["Incapacité", "Incapacitate"] },
  { key: "incite_01_a", aliases: ["Charnier", "Mass Grave"] },
  { key: "increased_explosive_power_a", aliases: ["Charges", "Ordre du général", "General's Order"] },
  { key: "infestation_01", aliases: ["Infection", "Infestation"] },
  { key: "insignia_of_blood", aliases: ["Insigne de sang", "Insignia of Blood"] },
  { key: "inspiration1", aliases: ["Sagesse des âges"] },
  { key: "inspiration2", aliases: ["Unknown"] },
  { key: "inspiration3", aliases: ["Unknown"] },
  { key: "intense_flames", aliases: ["Fulmination", "Fulminate"] },
  { key: "interdict_01", aliases: ["Interdiction", "Interdict"] },
  { key: "internalizeheat1", aliases: ["Inferno"] },
  { key: "internalizeheat3b", aliases: ["Élémentaire de Feu", "Brandon d'âme", "Soul Brand"] },
  { key: "intervene2", aliases: ["Effort conjoint", "Combined Effort"] },
  { key: "intimidatingweapon2", aliases: ["Frappe de fer", "Strike Like Iron"] },
  { key: "invigorate1", aliases: ["Poussée d'essence", "Essence Surge"] },
  { key: "invigorate2", aliases: ["Guérison naturelle", "Natural Healing"] },
  { key: "invigoration2a", aliases: ["Égide d'arcane", "Armure vivante", "Arcane Aegis", "Living Armor"] },
  { key: "invigoration3a", aliases: ["Restauration", "Restore"] },
  { key: "invoker_prerogative1", aliases: ["Forme de liche", "Scission terrestre", "Lich Form", "Earthen Sunder"] },
  { key: "ironskin1", aliases: ["Élémentaire de Terre mineur"] },
  { key: "ironwill1", aliases: ["Concentration mentale", "Les mots justes", "Mental Focus", "Moving Words"] },
  { key: "ironwill2", aliases: ["Courage de l'aigle", "Courage of the Eagle"] },
  { key: "jaggedlighting1", aliases: ["Unknown"] },
  { key: "jolting_wave", aliases: ["Jolting Wave"] },
  { key: "keen_eye", aliases: ["Prédateur du sommet", "Expérience du champ de bataille", "Apex Predator", "Battlefield Experience"] },
  { key: "kick1", aliases: ["Coup de pied retentissant"] },
  { key: "kick4", aliases: ["Fleet of Foot"] },
  { key: "killer_instinct", aliases: ["Unknown"] },
  { key: "kiss_of_life", aliases: ["Baiser de Vie", "Kiss of Life"] },
  { key: "lance1", aliases: ["Munitions électrifiées", "Electrified Munitions"] },
  { key: "lance1_a", aliases: ["Munitions de choc statique"] },
  { key: "land_mines", aliases: ["Cartouchière sans fond", "Bottomless Bandolier"] },
  { key: "latent_blaze", aliases: ["Embrasement latent", "Latent Blaze"] },
  { key: "layinghands1", aliases: ["Bourrasque revigorante", "Invigorating Gale"] },
  { key: "layinghands1x", aliases: ["Unknown"] },
  { key: "layonhands2", aliases: ["Contact de la nature", "Nature's Touch"] },
  { key: "layonhands2a", aliases: ["Estuaire", "Estuary"] },
  { key: "layonhands2z", aliases: ["Embruns de soins", "Décharge", "Vigueur précipitée", "Healing Spray", "Discharge", "Hastening Vigor"] },
  { key: "layonhands3", aliases: ["Unknown"] },
  { key: "liberation_treatment", aliases: ["Liberation Treatment"] },
  { key: "life-drain3", aliases: ["Instincts de prédateur", "Predatory Instincts"] },
  { key: "life_and_death_concord_b", aliases: ["Conversion d'essence", "Essence Conversion"] },
  { key: "lighting1", aliases: ["Jolt"] },
  { key: "lighting2", aliases: ["Explosion de tonnerre", "Ekkehard's Grasp"] },
  { key: "lighting2a", aliases: ["Lightning Strike"] },
  { key: "lighting_fury", aliases: ["Dispersion de choc", "Fureur foudroyante", "Lightning Fury", "Shock Dispersal"] },
  { key: "lighting_fury_a", aliases: ["Aiguillon neuronal", "Arc", "Neural Prod"] },
  { key: "lightingbolt4", aliases: ["Champ de foudre", "Lightning Field"] },
  { key: "lightingbolt5", aliases: ["Cascade d'électricité", "Electricity Cascade"] },
  { key: "living_flame_01", aliases: ["Flamme vivante", "Living Flame"] },
  { key: "long_range_bombing", aliases: ["Rage du Protecteur", "Patron's Rage"] },
  { key: "loot_gold_coins", aliases: ["Appel de cupidité", "Greed's Call"] },
  { key: "maelstrom", aliases: ["Maelström", "Tourbillon", "Voie de l'air", "Œil de la Tempête", "Maelstrom", "Whirlpool", "Path of Air", "Eye of the Storm"] },
  { key: "maelstrom_a", aliases: ["Tempête imminente", "Gathering Storm"] },
  { key: "maelstrom_b", aliases: ["Chimiste de bataille", "Battle Chemist"] },
  { key: "maelstrom_blast_wave", aliases: ["Vague d'explosions", "Blast Wave"] },
  { key: "maelstrom_drown", aliases: ["Noyade", "Drown"] },
  { key: "maelstrom_effervescent_blast", aliases: ["Explosion effervescente", "Effervescent Blast"] },
  { key: "maelstrom_excoriate", aliases: ["Excoriation", "Excoriate"] },
  { key: "maelstrom_expulse", aliases: ["Expulsion", "Expulse"] },
  { key: "maelstrom_flamewalker", aliases: ["Marcheflammes", "Flamewalker"] },
  { key: "maelstrom_flashpoint_beacon", aliases: ["Balise de point d'ignition", "Summon: Flashpoint Beacon"] },
  { key: "maelstrom_font_of_sublimation", aliases: ["Fontis de sublimation", "Font of Sublimation"] },
  { key: "maelstrom_pressurize", aliases: ["Pressurisation", "Pressurize"] },
  { key: "maelstrom_scald", aliases: ["Brûleur", "Scald"] },
  { key: "maelstrom_searingplasma", aliases: ["Plasma incandescent", "Searing Plasma"] },
  { key: "maelstrom_subsume", aliases: ["Subsomption", "Subsume"] },
  { key: "maelstrom_thresher", aliases: ["Avatar primitif : Renard des mers", "Primal Avatar: Thresher"] },
  { key: "maelstrom_vaporize", aliases: ["Vaporiser", "Vaporize"] },
  { key: "magicitem4a", aliases: ["Ténèbres suintantes", "Seeping Darkness"] },
  { key: "magicresist1", aliases: ["Flammes absorbantes", "Leeching Flames"] },
  { key: "magicresist2", aliases: ["Transe tempétueuse", "Storm Locus"] },
  { key: "magicresist2a", aliases: ["Paix intérieure", "Inner Peace"] },
  { key: "magicresist3", aliases: ["Unknown"] },
  { key: "magicward1", aliases: ["Protection spirituelle"] },
  { key: "magicward1a", aliases: ["Reflective Presence"] },
  { key: "magicward2", aliases: ["Bannissement", "Banish"] },
  { key: "magicward3", aliases: ["Éclair de rayonnement", "Flash of Radiance"] },
  { key: "magicward4", aliases: ["Brise-sort", "Sigil of Binding"] },
  { key: "magnify_pain_01", aliases: ["Fléau"] },
  { key: "maintenance_therapy", aliases: ["Thérapie d'entretien", "Maintenance Therapy"] },
  { key: "malicious_strike_01_a", aliases: ["Frappe artérielle", "Arterial Strike"] },
  { key: "manachannel1", aliases: ["Déchirement de mana", "Inquisition agressive", "Mana Wrench", "Aggressive Inquisition"] },
  { key: "manadrain1", aliases: ["Flamboiement mental", "Mental Flare"] },
  { key: "manadrain1a", aliases: ["Fil du destin", "Thread of Fate"] },
  { key: "mass_blood_transfusion", aliases: ["Mass Blood Transfusion"] },
  { key: "mass_casualty_response", aliases: ["Premiers soins de masse", "Mass Casualty Response"] },
  { key: "mass_oppression", aliases: ["Oppression de masse", "Mass Oppression"] },
  { key: "mass_rescue", aliases: ["Mass Rescue"] },
  { key: "mass_subdue", aliases: ["Unknown"] },
  { key: "massive_therapy", aliases: ["Thérapie intensive", "Massive Therapy"] },
  { key: "master_archer_b", aliases: ["Éradication", "Eradicate"] },
  { key: "medical_facility", aliases: ["Dextérité médicale", "Medical Facility"] },
  { key: "medicinal_leeching", aliases: ["Saignée curative", "Medicinal Leeching"] },
  { key: "memory_capture", aliases: ["Bouclier protecteur", "Memory Capture", "Protective Shield"] },
  { key: "menacingroar1", aliases: ["Invocation de Wyverne vicieuse inférieure"] },
  { key: "menacingroar2", aliases: ["Dernier souffle", "Instincts férals", "Last Gasp", "Feral Instincts"] },
  { key: "menacingroar2a", aliases: ["Mort hurlante", "Howling Death"] },
  { key: "menacingroar4b", aliases: ["Déficience spirituelle"] },
  { key: "mend1", aliases: ["Marqué par la lumière", "Marked by the Light"] },
  { key: "mend1c", aliases: ["Purification de la nature", "Expulsion de faveur", "Expulsis malis", "Nature's Cleansing", "Expel Boon", "Expel Harm"] },
  { key: "mend1f", aliases: ["Unknown"] },
  { key: "mend2b", aliases: ["Floraison", "Flourish"] },
  { key: "mend4a", aliases: ["Liaison vitale", "Life Bond"] },
  { key: "mirrorandsmoke2", aliases: ["Glassy Reflection"] },
  { key: "misdirection", aliases: ["Détournement de menace", "Locus de destruction", "Locus of Destruction"] },
  { key: "mortalshot1", aliases: ["Munitions vampiriques"] },
  { key: "mortalshot1b", aliases: ["Munitions à pointe d'argent"] },
  { key: "mortalshot2", aliases: ["Tir barbelé", "Barbed Shot"] },
  { key: "motif_of_bravery", aliases: ["Motif of Bravery"] },
  { key: "motif_of_encouragement", aliases: ["Motif d'encouragement", "Overflowing Renewal", "Motif of Encouragement"] },
  { key: "motif_of_regeneration_a", aliases: ["Motif of Regeneration"] },
  { key: "motif_of_tenacity", aliases: ["Motif of Tenacity"] },
  { key: "necromancer-corpse_explosion", aliases: ["Explosion cadavérique", "Corpse Explosion"] },
  { key: "necromancer-feign_death", aliases: ["Mort simulée", "Feign Death"] },
  { key: "necromancer-summon_zealot", aliases: ["Unknown"] },
  { key: "necromancer-summon_zealot_a", aliases: ["Invocation : Zélote squelettique majeur"] },
  { key: "necromancer_condemn", aliases: ["Condamnation", "Condemn"] },
  { key: "necromancer_detonate_bones_02_a", aliases: ["Frénésie d'os", "Corruption terrible", "Bone Frenzy", "Dire Corruption"] },
  { key: "necropotence1", aliases: ["Empowered Darkness"] },
  { key: "necropotence2", aliases: ["Maladie de l'âme", "Soul Sickness"] },
  { key: "necropotence4", aliases: ["Douleur obsédante", "Coup profanateur", "Haunting Pain", "Desecrating Blow"] },
  { key: "necropotence4a", aliases: ["Blessures nécrotiques", "Frappe crépusculaire", "Dusk Strike", "Necrotic Wounds"] },
  { key: "necropotence4z", aliases: ["Consommation", "Consumption"] },
  { key: "neutralize", aliases: ["Neutralisation"] },
  { key: "nightblade_blazing_path", aliases: ["Chemin brûlant", "Blazing Path"] },
  { key: "nightblade_dark_descent", aliases: ["Lien d'Âme"] },
  { key: "nightblade_dark_descent_a", aliases: ["Descente noire", "Dark Descent"] },
  { key: "nightstalker_01", aliases: ["Coucher de lune", "Setting Moon"] },
  { key: "nysyrs_rebuke", aliases: ["Appel de sang", "Cible précise", "Réprimande de Nysyr", "Nysyr's Rebuke", "Call of Blood", "Precise Target"] },
  { key: "opportunity_01_a", aliases: ["Énergie vivante", "Living Energy"] },
  { key: "overwhelm1a", aliases: ["Accablement", "Ruée de la jungle", "Overwhelm", "Jungle Rush"] },
  { key: "overwhelming_brilliance_01", aliases: ["Bénédiction de lumière", "Mien of Honor", "Light's Benediction"] },
  { key: "paladin-graceful_under_pressure_a", aliases: ["Agonie partagée"] },
  { key: "paladin-life_rapture", aliases: ["Barrage élémentaire", "Elemental Barrage"] },
  { key: "paladin-life_rapture_a", aliases: ["Blâme", "Censure"] },
  { key: "paladin-preservation", aliases: ["Accolade resplendissante"] },
  { key: "paladin-preservation_b", aliases: ["Assurance-vie", "Meditative Trance", "Life Insurance"] },
  { key: "paladin-reprisal", aliases: ["Défense juste", "Just Defense", "Light's Reprisal"] },
  { key: "paladin-vengeful_wrath", aliases: ["Défense de l'arme"] },
  { key: "paladin_lights_blessing_b", aliases: ["Faveur de lumière", "Light's Blessing"] },
  { key: "paladin_shield_of_the_vengeful", aliases: ["Intercession", "Intercede"] },
  { key: "paragon-improved_predicatable_movements_b", aliases: ["Armure d'os", "Bone Armor"] },
  { key: "paragon-predicatable_movements_a", aliases: ["Predictable Movements"] },
  { key: "paragon-way_of_mountain_a", aliases: ["Unknown"] },
  { key: "paragon-way_of_mountain_c", aliases: ["Grand froid", "Deep Freeze"] },
  { key: "paragon_alacricity", aliases: ["Fiery Will"] },
  { key: "paragon_alacricity_a", aliases: ["Empressement", "Alacrity"] },
  { key: "paragon_analyze_weakness_b", aliases: ["Unknown"] },
  { key: "paragon_analyze_weakness_e", aliases: ["Tir d'adresse", "Skill Shot"] },
  { key: "paragon_feint", aliases: ["Capture d'offensive", "Notion Theft"] },
  { key: "paragon_path_of_the_tempest_01_a", aliases: ["Frappe doublée", "Double Strike"] },
  { key: "paragon_shifting_blades_01", aliases: ["Lames changeantes", "Frappe binaire", "Binary Strike", "Shifting Blades"] },
  { key: "paragon_way_of_the_river_01", aliases: ["Voie de la rivière", "Way of the River"] },
  { key: "paragon_way_of_the_river_01_a", aliases: ["Oversaturation"] },
  { key: "paralyzing_strike_01", aliases: ["Frappe paralysante", "Coup dévorant", "Paralyzing Strike", "Devouring Blow"] },
  { key: "persecute", aliases: ["Persécution"] },
  { key: "perseverance", aliases: ["Persévérance", "Perseverance"] },
  { key: "pet_dire-wolf", aliases: ["Loup féroce", "Call: Dire Wolf"] },
  { key: "pet_dire-wolf_a", aliases: ["Call: Greater Dire Wolf"] },
  { key: "pet_raptor", aliases: ["Call: Blood Raptor"] },
  { key: "pet_razorbeast", aliases: ["Bête-tranchante", "Call: Razorbeast"] },
  { key: "pet_razorbeast_a", aliases: ["Bête-tranchante supérieure", "Call: Greater Razorbeast"] },
  { key: "phantom_blow_a", aliases: ["Coup fantôme", "Phantom Blow"] },
  { key: "piercing_shot_01", aliases: ["Munitions déchirantes", "Rending Munitions"] },
  { key: "piercing_shot_01_a", aliases: ["Unknown"] },
  { key: "piercingenergy3", aliases: ["Contact de Mort", "Death Touch"] },
  { key: "piety2a", aliases: ["Provoke"] },
  { key: "piety3", aliases: ["Altruisme renouvelé"] },
  { key: "pin_down_01", aliases: ["Unknown"] },
  { key: "plague_01_a", aliases: ["Semeur de peste", "Plague Bringer"] },
  { key: "plant14a", aliases: ["Éclosion", "Bloom"] },
  { key: "plant1a", aliases: ["Fouet de vignes", "Vine Whip"] },
  { key: "plant3b", aliases: ["Lianes desséchantes"] },
  { key: "plant3c", aliases: ["Vignes rampantes", "Creeping Vines"] },
  { key: "plasma_strike", aliases: ["Pointe de rage", "Frappe de plasma", "Rage Spike", "Plasma Strike"] },
  { key: "poison_gas_01", aliases: ["Gaz empoisonné", "Spores corrosives", "Corrosive Spores"] },
  { key: "poison_gas_01_a", aliases: ["Blinding Powder"] },
  { key: "poison_gas_02", aliases: ["Nécrose", "Necrosis"] },
  { key: "poisoned", aliases: ["Ombres dévorantes", "Infection virale", "Devouring Shadows"] },
  { key: "poisoned_a", aliases: ["Fatalité rampante", "Creeping Doom"] },
  { key: "poisonone2a", aliases: ["Lethal Poison"] },
  { key: "poisonone2b", aliases: ["Unknown"] },
  { key: "poisontwo1", aliases: ["Crochet de crotale", "Serpent Tooth"] },
  { key: "poisontwo2a", aliases: ["Avatar primitif : Ouroboros", "Primal Avatar: Ouroboros"] },
  { key: "poisontwo3", aliases: ["Breuvage revigorant", "Enduring Brew"] },
  { key: "poisontwo4", aliases: ["Unknown"] },
  { key: "positive_reaction", aliases: ["Réaction positive"] },
  { key: "positive_reaction_a", aliases: ["Balise de protection de Vie", "Cycle de la Vie", "Summon: Lifewarding Beacon", "Circle of Life"] },
  { key: "power_chord", aliases: ["Accord de puissance", "Alignement transversal", "Leyline Traversal"] },
  { key: "power_chord_a", aliases: ["Cadenza"] },
  { key: "power_chord_b", aliases: ["Chevaucher l'éclair"] },
  { key: "preemptive_therapy", aliases: ["Thérapie préemptive"] },
  { key: "preventive_medication", aliases: ["Unknown"] },
  { key: "primal_avatar_deer", aliases: ["Avatar primitif : Esprit de cerf", "Primal Avatar: Deer Spirit"] },
  { key: "primal_avatar_drake", aliases: ["Avatar primitif : Drake", "Invocation de Wyverne vicieuse supérieure", "Primal Avatar: Drake"] },
  { key: "primal_avatar_griffon", aliases: ["Avatar primitif : Griffon", "Primal Avatar: Griffon"] },
  { key: "primal_avatar_ram", aliases: ["Avatar primitif : Bélier", "Primal Avatar: Ram"] },
  { key: "primal_avatar_tiger", aliases: ["Avatar primitif - Tigre", "Primal Avatar: Tiger"] },
  { key: "primal_avatar_wind_serpent", aliases: ["Avatar primitif : Serpent du Vent", "Primal Avatar: Wind Serpent"] },
  { key: "primal_death_01", aliases: ["Floraison mortelle", "Desecrate", "Death Blossom"] },
  { key: "primalavatarpredator", aliases: ["Avatar primitif : Raptor", "Primal Avatar: Raptor"] },
  { key: "primalavatarwolf", aliases: ["Avatar primitif : Loup", "Primal Avatar: Wolf"] },
  { key: "primalist_font_of_wit", aliases: ["Fontis de présence d'esprit", "Font of Wit"] },
  { key: "primalist_molten_wave", aliases: ["Vague en fusion", "Molten Wave"] },
  { key: "primalist_temper", aliases: ["Modération", "Temper"] },
  { key: "primalist_torrential_rain", aliases: ["Pluie torrentielle", "Torrential Rain"] },
  { key: "primalistfarseer", aliases: ["Unknown"] },
  { key: "primalistmythic", aliases: ["Unknown"] },
  { key: "primalistpredator", aliases: ["Unknown"] },
  { key: "primallord", aliases: ["Unknown"] },
  { key: "prolonged_recovery", aliases: ["Récupération prolongée", "Épicentre", "Epicenter"] },
  { key: "provoke1", aliases: ["Griffe de panthère", "Panther Claw"] },
  { key: "puncture1", aliases: ["Perforation de Scorpion", "Scorpion Pierce"] },
  { key: "puncture2", aliases: ["Poison affaiblissant", "Enfeebling Poison"] },
  { key: "purge", aliases: ["Barrage de Faille", "Rift Barrage"] },
  { key: "purge_a", aliases: ["Purge", "Impulsion à retardement", "Delayed Pulse"] },
  { key: "purifier_firewall_a", aliases: ["Pare-feu", "Fire Wall"] },
  { key: "purifier_sign_of_anticipation_b", aliases: ["Signe d'anticipation", "Sign of Anticipation"] },
  { key: "purifier_sign_of_daring_a", aliases: ["Signe d'audace", "Sign of Daring"] },
  { key: "purifier_sign_of_faith", aliases: ["Insigne de protection", "Insignia of Protection"] },
  { key: "purifier_sign_of_faith_cc", aliases: ["Éléments précipités", "Signe de foi", "Sign of Faith"] },
  { key: "purifier_sign_of_wrath_a", aliases: ["Signe de courroux", "Sign of Wrath"] },
  { key: "purifier_symbol_of_the_sun", aliases: ["Unknown"] },
  { key: "purifier_symbol_of_the_torch_a", aliases: ["Unknown"] },
  { key: "pyroclasty2", aliases: ["Compte à rebours", "Countdown"] },
  { key: "quick_reload_a", aliases: ["Recharge rapide", "Quick Reload"] },
  { key: "quick_remedy", aliases: ["Unknown"] },
  { key: "rainofarrows1", aliases: ["Dispersion", "Fan Out"] },
  { key: "rainofarrows2", aliases: ["Unknown"] },
  { key: "rainofarrows4a", aliases: ["Crossfire"] },
  { key: "rally1", aliases: ["Flots purificateurs", "Barrière élémentaire", "Cleansing Waters", "Elemental Barrier"] },
  { key: "rally1a", aliases: ["Flots curatifs", "Bouclier d'énergie", "Curative Waters", "Power Shield"] },
  { key: "rally1x", aliases: ["Gloire des Élus", "Glory of the Chosen"] },
  { key: "rally3", aliases: ["Faveur de maréchal"] },
  { key: "rampage1", aliases: ["Frappe galvanisante", "Empowering Strike"] },
  { key: "ranged_bow_020", aliases: ["Maîtrise des armes à distance", "Ranged Weapon Mastery"] },
  { key: "rapid_setup", aliases: ["Volée de flammes", "Flame Volley"] },
  { key: "rapidshot1", aliases: ["Unknown"] },
  { key: "rapidshot1a", aliases: ["Tir instantané", "Rapid Fire Shot"] },
  { key: "rapidshot2", aliases: ["Feu de l'ombre"] },
  { key: "rapidshot3", aliases: ["Hasted Shot"] },
  { key: "rapidshot4", aliases: ["Unknown"] },
  { key: "rapidshot4a", aliases: ["Empowered Shot"] },
  { key: "reaver_binding_of_devouring_darkness", aliases: ["Insigne de dilapidation"] },
  { key: "reaver_crest_of_shadow", aliases: ["Fureur guerrière", "Douleur résiduelle", "Battle Fury", "Residual Pain"] },
  { key: "reaver_explosive_infestation_a", aliases: ["Fléau", "Infection explosive", "Blight", "Explosive Infestation"] },
  { key: "reaver_explosive_infestation_b", aliases: ["Maître des poisons", "Master of Poisons"] },
  { key: "redirect1", aliases: ["Revers massif", "Mass Reversal"] },
  { key: "redirect1a", aliases: ["Dismiss Pet"] },
  { key: "redirect1b", aliases: ["Extraction féerique", "Fae Extraction"] },
  { key: "redirect2", aliases: ["Revers de fortune", "Reversal of Fortune"] },
  { key: "redirect2a", aliases: ["Unknown"] },
  { key: "redirect4a", aliases: ["Unknown"] },
  { key: "redirect4b", aliases: ["Rebuke"] },
  { key: "redress", aliases: ["Redressement"] },
  { key: "reign_of_despair", aliases: ["Puits des âmes"] },
  { key: "releaseheat3a", aliases: ["Bouclier brûlant", "Burning Shield"] },
  { key: "releaseheat4b", aliases: ["Charge intériorisée", "Internalize Charge"] },
  { key: "releaseheat4c", aliases: ["Matérialisation d'âme", "Materialize Soul"] },
  { key: "remote_clipping_a", aliases: ["Esquive", "Elude", "Freezing Gust"] },
  { key: "removeheat1", aliases: ["Coup de vent glacial", "Icy Gale"] },
  { key: "repelling_shot", aliases: ["Repelling Shot"] },
  { key: "reprieve_01", aliases: ["Unknown"] },
  { key: "reprieve_01a", aliases: ["Marche de Vie", "Lifewalk"] },
  { key: "requital_01", aliases: ["Flowing Sand"] },
  { key: "requital_01_a", aliases: ["Mien of Leadership"] },
  { key: "ressurect4bl", aliases: ["Fleuve de Vie", "Faux repos", "False Repose"] },
  { key: "ressurect4y", aliases: ["Life's Return"] },
  { key: "ressurection1b", aliases: ["Préscience", "Prescience"] },
  { key: "ressurection1za", aliases: ["Éclair du Phénix", "Flash of the Phoenix"] },
  { key: "ressurection3bb", aliases: ["Impératif du juste"] },
  { key: "restorative_flame", aliases: ["Unknown"] },
  { key: "restorative_flame2", aliases: ["Unknown"] },
  { key: "restore1b", aliases: ["Fontis de vitalité", "Font of Vitality"] },
  { key: "restore2b", aliases: ["Invocation subtile"] },
  { key: "resurrect4da", aliases: ["Voile animique", "Soul Shroud"] },
  { key: "retreat", aliases: ["Retraite"] },
  { key: "revitalize1c", aliases: ["Harmonie de l'âme et de la lame", "Blade and Soul Parity"] },
  { key: "ricochet1", aliases: ["Unknown"] },
  { key: "riff", aliases: ["Unknown"] },
  { key: "rift_affinity", aliases: ["Planebound Resilience"] },
  { key: "rift_prison", aliases: ["Unknown"] },
  { key: "riftblade-avatar_of_water", aliases: ["Élémentaire d'Eau"] },
  { key: "riftblade-avatar_of_water_a", aliases: ["Avatar de l'Eau", "Avatar of Water"] },
  { key: "riftblade-earth_burst", aliases: ["Balise du Drake", "Summon: Beacon of the Drake"] },
  { key: "riftblade-earth_burst_a", aliases: ["Explosion terrestre", "Réplique", "Earth Burst", "Aftershock"] },
  { key: "riftblade-earth_burst_b", aliases: ["Remue-ménage", "Upheaval"] },
  { key: "riftblade-surging_energy", aliases: ["Illumination", "Illuminate"] },
  { key: "riftblade-surging_energy_b", aliases: ["Planar Disruption"] },
  { key: "riftblade-surging_energy_c", aliases: ["Choc foudroyant", "Thunder Shock"] },
  { key: "riftblade_frost_strike_01", aliases: ["Éclair foudroyant"] },
  { key: "riftblade_frost_strike_01_a", aliases: ["Frappe glacée", "Fureur glacée", "Frost Strike", "Icy Fury"] },
  { key: "riftblade_stone_shield_01_b", aliases: ["Bouclier de pierre"] },
  { key: "riftblade_stone_shield_01_f", aliases: ["Broyage cristallin", "Crystalline Smash"] },
  { key: "riftblade_thunder_strike_01", aliases: ["Frappe de tonnerre", "Contrechoc", "Counter Shock"] },
  { key: "riftstalker_great_fortitude_01", aliases: ["Linceul d'agonie", "Loyal Minion"] },
  { key: "riftstalker_great_fortitude_01_a", aliases: ["Linceul d'agonie"] },
  { key: "riftstalker_great_fortitude_01_b", aliases: ["Infusion"] },
  { key: "riftstalker_planar_refuge_01_a", aliases: ["Planar Refuge", "Battle Surge"] },
  { key: "riftstalker_planar_repulsion_01", aliases: ["Accord de la Faille", "Accord of the Rift"] },
  { key: "riftstalker_planar_repulsion_01_a", aliases: ["Attraction planaire", "Précellence", "Planar Attraction", "Dominion"] },
  { key: "riftstalker_planebound_aegis", aliases: ["Égide liée à un Plan", "Planebound Aegis"] },
  { key: "riftstalker_planebound_aegis_b", aliases: ["Égide de mana", "Explosion défensive", "Defensive Surge"] },
  { key: "riftstalker_rift_scavenger_01_a", aliases: ["Taillade morbide", "Morbid Slash"] },
  { key: "riftstalker_soul_coalescense_a", aliases: ["Unknown"] },
  { key: "riftstalker_toughened_soul_01", aliases: ["Bien-être physique", "Physical Wellness"] },
  { key: "riftstalker_toughened_soul_01_a", aliases: ["Peur primitive", "Primal Fear"] },
  { key: "righteous_invocation_01", aliases: ["Doctrine de loyauté", "Frères d'armes", "Doctrine of Loyalty", "Brothers in Arms"] },
  { key: "righteousness1", aliases: ["Lamentation du prêtre", "Coup par surprise", "Priest's Lament", "Blindside"] },
  { key: "righteousness2", aliases: ["Stature dominante", "Décret divin", "Interdiction de mourir", "Towering Stature", "Divine Edict"] },
  { key: "righteousness2a", aliases: ["Unknown"] },
  { key: "rod8d", aliases: ["Pilum cristallin", "Crystalline Lance"] },
  { key: "rogue_shadow_shift", aliases: ["Dégénération", "Désintégration", "Inéluctable", "Degeneration", "Disintegration", "Inescapable"] },
  { key: "rogueshot1", aliases: ["Tir calculé", "Calculated Shot"] },
  { key: "roguestrike1", aliases: ["Déchiquetage", "Jagged Strike"] },
  { key: "roguestrike1a", aliases: ["Coup redoutable", "Dire Blow"] },
  { key: "roguestrike2a", aliases: ["Frappe distrayante", "Frappe meurtrière", "Nervosité", "Deadly Strike", "Flinching Strike", "Unnerve"] },
  { key: "runeshaper_rune_aggression", aliases: ["Rune d'énergie supérieure", "Greater Rune of Energy"] },
  { key: "runeshaper_rune_agony", aliases: ["Grande Rune d'agonie", "Greater Rune of Agony"] },
  { key: "runeshaper_rune_castigation", aliases: ["Rune de castigation", "Rune of Castigation"] },
  { key: "runeshaper_rune_power", aliases: ["Rune de pouvoir", "Rune of Power"] },
  { key: "runeshaper_rune_soul_binding", aliases: ["Rune de lien d'âme", "Rune of Soul Binding"] },
  { key: "runeshaper_rune_travail", aliases: ["Rune de labeur", "Rune of Travail"] },
  { key: "runeshaper_runefall", aliases: ["Chute de runes", "Runefall"] },
  { key: "runeshaper_runelords_inscription", aliases: ["Inscription du Seigneur des runes", "Runelord's Inscription"] },
  { key: "runeshaper_runestrike", aliases: ["Frappe de runes", "Runestrike"] },
  { key: "runeshaper_seal_imprisonment", aliases: ["Grande Rune d'emprisonnement", "Greater Rune of Imprisonment"] },
  { key: "runeshaper_seal_pain", aliases: ["Sceau de douleur", "Seal of Pain"] },
  { key: "runeshaper_seal_vulnerability", aliases: ["Unknown"] },
  { key: "runshaper_impending_doom", aliases: ["Rune de l'étreinte de la mort", "Rune of Impending Doom"] },
  { key: "runshaper_inscribe_fate", aliases: ["Destin inscrit", "Tempête d'éclairs arcaniques", "Inscribe Fate", "Arcane Bolt Storm"] },
  { key: "runshaper_mobility", aliases: ["Rune de mobilité supérieure", "Greater Rune of Mobility"] },
  { key: "runshaper_rune_prison", aliases: ["Prison de rune", "Rune Prison"] },
  { key: "runshaper_rune_smiting", aliases: ["Rune de frappe ferme", "Rune of Smiting"] },
  { key: "runshaper_rune_vessel", aliases: ["Lanterne runique", "Rune Vessel"] },
  { key: "runshaper_seal_enchantment", aliases: ["Sceau d'amélioration", "Seal of Enhancement"] },
  { key: "ruthless_stalker", aliases: ["Choc", "Coup étourdissant", "Shock", "Dazing Blow"] },
  { key: "saboteur_cloud_maker", aliases: ["Nébulisation", "Cloud Maker"] },
  { key: "saboteur_molotov_cocktail", aliases: ["Charge de sacoche", "Satchel Charge"] },
  { key: "sacrificepet1", aliases: ["Ignite"] },
  { key: "sacrificepet2a", aliases: ["Animaclaste", "Shatter Soul"] },
  { key: "sacrificepet3", aliases: ["Unknown"] },
  { key: "sacrificepet4a", aliases: ["Fell Blades"] },
  { key: "sacrificepet4b", aliases: ["Unknown"] },
  { key: "sanction_heretic", aliases: ["Unknown"] },
  { key: "sanction_heretic_a", aliases: ["Sanction d'hérétique", "Sanction", "Sanction Heretic"] },
  { key: "scatter_strike", aliases: ["Frappe dispersive"] },
  { key: "scatter_the_shadows", aliases: ["Dispersion des ombres"] },
  { key: "scourge_of_darkness_01", aliases: ["Bourbier trébuchant"] },
  { key: "scourge_of_darkness_01_a", aliases: ["Fléau des Ténèbres", "Vrilles mortelles", "Deathly Tendrils"] },
  { key: "scrape2", aliases: ["Filets jumeaux"] },
  { key: "scrape3", aliases: ["Cutting Slash"] },
  { key: "secondwind1", aliases: ["Étranglement", "Choke"] },
  { key: "secondwind1a", aliases: ["Supervision spirituelle", "Spiritual Guidance"] },
  { key: "secondwind2", aliases: ["Frisson venteux", "Brèche d'ouragan", "Wind Chill", "Hurricane Breach"] },
  { key: "secondwind2a", aliases: ["Unknown"] },
  { key: "sentinel-cleansing_prayer", aliases: ["Unknown"] },
  { key: "sentinel-cleansing_prayer_b", aliases: ["Cautérisation", "Cauterize"] },
  { key: "sentinel-healing_benediction", aliases: ["Faith Rewarded"] },
  { key: "sentinel-healing_benediction_b", aliases: ["Espoir de Nyol"] },
  { key: "sentinel-healing_benediction_f_5", aliases: ["Élévation", "Uplift"] },
  { key: "sentinel-protect_the_flock_a", aliases: ["Coup d'éclat", "Archon's Bulwark", "Stroke of Brilliance"] },
  { key: "sentinel-refreshing_communion", aliases: ["Hâte du guérisseur", "Healer's Haste"] },
  { key: "sentinel_wrathful_exuberance", aliases: ["Biosyndesmos", "Biofeedback"] },
  { key: "sentinel_wrathful_exuberance_cc", aliases: ["Exubérance courroucée"] },
  { key: "sentinel_wrathful_exuberance_e", aliases: ["Sérénité", "Serenity"] },
  { key: "shadeborn_bond_darkness", aliases: ["Lien de nuit", "Bond of Night"] },
  { key: "shadeborn_bottomless_void", aliases: ["Néant des profondeurs infinies", "Bottomless Void"] },
  { key: "shadeborn_consuming_depths", aliases: ["Profondeurs dévorantes", "Consuming Depths"] },
  { key: "shadeborn_inescapable_bond", aliases: ["Lien inéluctable", "Inescapable Bond"] },
  { key: "shadeborn_innumerable_shadows", aliases: ["Ombres innombrables", "Innumerable Shadows"] },
  { key: "shadeborn_meld_darkness", aliases: ["Fusion avec les ténèbres", "Meld Into Darkness"] },
  { key: "shadeborn_mirrored_strike", aliases: ["Frappe reflétée", "Mirrored Strike"] },
  { key: "shadeborn_nexus_darkness", aliases: ["Nexus de Ténèbres", "Nexus of Darkness"] },
  { key: "shadeborn_scything_night", aliases: ["Nuit de la faux", "Scything Night"] },
  { key: "shadeborn_shadow_assault", aliases: ["Déluge d'ombre", "Shadow Flurry"] },
  { key: "shadeborn_shadow_grip", aliases: ["Emprise d'ombre", "Shadow Grip"] },
  { key: "shadeborn_shadow_lash", aliases: ["Fouet d'ombre", "Shadow Lash"] },
  { key: "shadeborn_shadow_restoration", aliases: ["Restauration d'ombre", "Shadow Restoration"] },
  { key: "shadeborn_strangulate", aliases: ["Étranglement", "Strangulate"] },
  { key: "shadeborn_sudden_appearance", aliases: ["Apparition soudaine", "Sudden Appearance"] },
  { key: "shadeborn_void_touch", aliases: ["Contact du Vide", "Void Touch"] },
  { key: "shadow_assault", aliases: ["Frappe de Faille", "Assaut d'ombre", "Oblitération concentrée", "Rift Strike", "Focused Obliteration"] },
  { key: "shadow_assault_a", aliases: ["Force des plans", "Power of the Planes", "Death from the Shadows"] },
  { key: "shadow_blitz_a", aliases: ["Attaque de l'ombre"] },
  { key: "shadow_blitz_b", aliases: ["Malédiction de l'anarchie", "Deathly Pall", "Curse of Anarchy"] },
  { key: "shadow_shift_b", aliases: ["Unknown"] },
  { key: "shadow_shift_c", aliases: ["Fae Step"] },
  { key: "shadow_stalk", aliases: ["Guet de l'ombre", "Inversion de Faille", "Rift Reversal"] },
  { key: "shadow_warp", aliases: ["Accord de Changement", "Accord of Shifting"] },
  { key: "shadow_warp_b", aliases: ["Passage sombre", "Marche forcée", "Dark Passage", "Forced March"] },
  { key: "shadow_warp_e", aliases: ["Lié", "Bound"] },
  { key: "shaman-courage_of_the_bear", aliases: ["Courage de l'ours", "Fureur de l'ours", "Courage of the Bear", "Bear's Fury"] },
  { key: "shaman-courage_of_the_bear_a", aliases: ["Agression férale", "Feral Aggression"] },
  { key: "shaman-courage_of_the_jaguar", aliases: ["Courage de la panthère", "Courage of the Panther"] },
  { key: "shaman-glacial_shield", aliases: ["Bouclier glacial", "Bouclier cristallin", "Glacial Shield", "Crystalline Shield"] },
  { key: "shaman-lighting_hammer", aliases: ["Lightning Hammer"] },
  { key: "shaman-vengeance_of_bitter_wind", aliases: ["Cisaille du vent", "Bitter Wind", "Wind Shear"] },
  { key: "shaman-vengeance_of_bitter_wind_a", aliases: ["Coupe-air", "Air Cutter"] },
  { key: "shaman-vengeance_of_frozen_earth", aliases: ["Explosion de Faille", "Rift Burst"] },
  { key: "shaman-vengeance_of_frozen_earth_a", aliases: ["Gré glacé", "Frozen Volition"] },
  { key: "shaman-vengeance_of_frozen_earth_b", aliases: ["Sol gelé", "Frozen Ground"] },
  { key: "shaman-vengeance_of_frozen_earth_c", aliases: ["Carapace de glace", "Froid engourdissant", "Icy Carapace", "Numbing Cold"] },
  { key: "shaman-vengeance_of_winter_storm", aliases: ["Unknown"] },
  { key: "shaman-vengeance_of_winter_storm_a", aliases: ["Explosion polaire", "Ordre glacial", "Icy Burst", "Icy Command"] },
  { key: "shatter1", aliases: ["Unknown"] },
  { key: "shatter3", aliases: ["Coup glacé", "Icy Blow", "Furious Rage"] },
  { key: "shattered_reflection", aliases: ["Unknown"] },
  { key: "shield_surge", aliases: ["Poussée de bouclier"] },
  { key: "shielding_charge", aliases: ["Unknown"] },
  { key: "shockwave1", aliases: ["Frappe incandescente"] },
  { key: "shockwave2", aliases: ["Frappe fervente", "Fervent Strike"] },
  { key: "shockwave2a", aliases: ["Coup massif", "Massive Blow"] },
  { key: "shockwave3", aliases: ["Lame-tempête"] },
  { key: "shockwave3d", aliases: ["Lame planaire", "Planar Blade"] },
  { key: "shockwave4", aliases: ["Matrice de recalibrage large"] },
  { key: "shreddingtrap4", aliases: ["Terre saisissante", "Grasping Earth"] },
  { key: "shroudofpenitent2", aliases: ["Délibération du juste", "Lumière de la rédemption", "Righteous Deliberation", "Light of Redemption"] },
  { key: "side_steps", aliases: ["Unknown"] },
  { key: "sigil_of_lurking_decay_b", aliases: ["Éclaboussure planaire", "Planar Splash"] },
  { key: "silent_footsteps_01_b", aliases: ["Unknown"] },
  { key: "simultaneous_treatment", aliases: ["Unknown"] },
  { key: "skeleton2c", aliases: ["Invocation : Chevalier squelettique majeur"] },
  { key: "skelf_bite", aliases: ["Gueule de batteur", "Thresher's Maw"] },
  { key: "slam2", aliases: ["Frappe de l'avalanche", "Avalanche Strike"] },
  { key: "slam3a", aliases: ["Frappe sauvage", "Coup destructeur", "Breaking Blow"] },
  { key: "slam4", aliases: ["Bombe volcanique"] },
  { key: "slam4a", aliases: ["Explosion ardente", "Fiery Burst"] },
  { key: "slip_away_03", aliases: ["Éclipse", "Sabotage furtif", "Manteau de la Mort", "Sabotage Run", "Cloak of Death"] },
  { key: "smelting1a", aliases: ["Rite de la forge", "Rite of the Forge"] },
  { key: "smite1", aliases: ["Condamnation"] },
  { key: "smite2", aliases: ["Frappe de rétribution", "Light's Hammer"] },
  { key: "smite4a", aliases: ["Frappe essentielle", "Essence Strike"] },
  { key: "smokeandmirrors1", aliases: ["Manœuvre défensive", "Defensive Maneuver"] },
  { key: "smokeandmirrors3", aliases: ["Puissance déclinante"] },
  { key: "smother_01", aliases: ["Étouffement", "Frappe dans le cou"] },
  { key: "soothe_the_flames", aliases: ["Sortie explosive", "Explosive Exit"] },
  { key: "soul_arbiter", aliases: ["Unknown"] },
  { key: "soul_archon", aliases: ["Unknown"] },
  { key: "soul_assassin", aliases: ["Unknown"] },
  { key: "soul_bard", aliases: ["Unknown"] },
  { key: "soul_beastmaster", aliases: ["Unknown"] },
  { key: "soul_berserker", aliases: ["Unknown"] },
  { key: "soul_bladedancer", aliases: ["Unknown"] },
  { key: "soul_cablist", aliases: ["Unknown"] },
  { key: "soul_champion", aliases: ["Unknown"] },
  { key: "soul_chloromancer", aliases: ["Unknown"] },
  { key: "soul_defiler", aliases: ["Unknown"] },
  { key: "soul_dervish", aliases: ["Unknown"] },
  { key: "soul_dominator", aliases: ["Unknown"] },
  { key: "soul_druid", aliases: ["Unknown"] },
  { key: "soul_elementalist", aliases: ["Unknown"] },
  { key: "soul_frostkeeper", aliases: ["Unknown"] },
  { key: "soul_harbinger", aliases: ["Unknown"] },
  { key: "soul_inquisitor", aliases: ["Unknown"] },
  { key: "soul_justicar", aliases: ["Unknown"] },
  { key: "soul_liberator", aliases: ["Unknown"] },
  { key: "soul_maelstrom", aliases: ["Unknown"] },
  { key: "soul_marksman", aliases: ["Unknown"] },
  { key: "soul_necromancer", aliases: ["Unknown"] },
  { key: "soul_nightblade", aliases: ["Unknown"] },
  { key: "soul_oracle", aliases: ["Unknown"] },
  { key: "soul_paragon", aliases: ["Don du Parangon", "Gift of the Paragon"] },
  { key: "soul_physician", aliases: ["Unknown"] },
  { key: "soul_preserver", aliases: ["Unknown"] },
  { key: "soul_purifier", aliases: ["Unknown"] },
  { key: "soul_pyromancer", aliases: ["Unknown"] },
  { key: "soul_ranger", aliases: ["Unknown"] },
  { key: "soul_reaver", aliases: ["Unknown"] },
  { key: "soul_redemption", aliases: ["Rédemption d'âme"] },
  { key: "soul_riftblade", aliases: ["Unknown"] },
  { key: "soul_riftstalker", aliases: ["Unknown"] },
  { key: "soul_runeshaper", aliases: ["Unknown"] },
  { key: "soul_saboteur", aliases: ["Unknown"] },
  { key: "soul_sentinel", aliases: ["Unknown"] },
  { key: "soul_shadeborn", aliases: ["Unknown"] },
  { key: "soul_shaman", aliases: ["Unknown"] },
  { key: "soul_stormcaller", aliases: ["Unknown"] },
  { key: "soul_tactician", aliases: ["Unknown"] },
  { key: "soul_tempest", aliases: ["Unknown"] },
  { key: "soul_titan", aliases: ["Unknown"] },
  { key: "soul_typhoon", aliases: ["Unknown"] },
  { key: "soul_voidknight", aliases: ["Unknown"] },
  { key: "soul_vulcanist", aliases: ["Unknown"] },
  { key: "soul_warchanter", aliases: ["Unknown"] },
  { key: "soul_warden", aliases: ["Unknown"] },
  { key: "soul_warlock", aliases: ["Unknown"] },
  { key: "soul_warlord", aliases: ["Unknown"] },
  { key: "souldrain1", aliases: ["Orage déchaîné", "Courant apaisant", "Raging Storm"] },
  { key: "souldrain3", aliases: ["Déshydratation", "Dehydrate"] },
  { key: "souldrain4", aliases: ["Appel d'outre-tombe", "Aspiration d'âme", "Empty the Crypts"] },
  { key: "spiritblast2", aliases: ["Rayon éthéré", "Ethereal Beam"] },
  { key: "spiritblast3", aliases: ["Étincelle"] },
  { key: "spiritblast4b", aliases: ["Trait de perversion", "Symbole de corruption", "Bolt of Depravity"] },
  { key: "spiritblast4bc", aliases: ["Trait de jugement", "Trait de précision", "Crystalline Missiles", "Bolt of Judgment", "Precision Bolt"] },
  { key: "spiritbolt1", aliases: ["Éclair de lumière", "Bolt of Light"] },
  { key: "spiritbolt2", aliases: ["Vents arrière", "Tailwind"] },
  { key: "spiritofcrusader1", aliases: ["Assaut furieux", "Furious Assault"] },
  { key: "spiritofcrusader2", aliases: ["Décret vengeur"] },
  { key: "spiritoflion3", aliases: ["Instincts de prédateur", "Appel primitif"] },
  { key: "spiritofmongoose2", aliases: ["Unknown"] },
  { key: "spiritofsaints1", aliases: ["Appel divin", "Divine Call"] },
  { key: "spiritofsaints3", aliases: ["Bénédiction du soigneur", "Caregiver's Blessing", "Command to Recover"] },
  { key: "spiritoftree1", aliases: ["Appel de la forêt", "Call of the Forest"] },
  { key: "spiritoftree1a", aliases: ["Croissance sauvage", "Apaisement", "Montée de colère", "Building Rage", "Calm Down"] },
  { key: "spiritofturtle2", aliases: ["Bouclier vivant", "Living Shell"] },
  { key: "spiritstrike5", aliases: ["Doctrine d'autorité", "Doctrine of Authority", "Pacifying Strike"] },
  { key: "spiritual_will", aliases: ["Cleansing Prayer"] },
  { key: "spiritual_willa", aliases: ["Destin inéluctable", "Impending Fate"] },
  { key: "staggeringshot3", aliases: ["Malicious Poison"] },
  { key: "stalking_phase_a", aliases: ["Unknown"] },
  { key: "static_shot", aliases: ["Unknown"] },
  { key: "stealth_w", aliases: ["Furtivité"] },
  { key: "stealth_z", aliases: ["Dissimulation", "Conceal"] },
  { key: "steelskin2", aliases: ["Élémentaire de Terre majeur"] },
  { key: "sterilize1_a", aliases: ["Rassemblement de flammes", "Gathering of Flames"] },
  { key: "stormcaller_lightning_arc", aliases: ["Arc de foudre", "Chaîne d'impulsions", "Lightning Arc", "Chain Pulse"] },
  { key: "stormcaller_lightning_storm_01", aliases: ["Unknown"] },
  { key: "stormcaller_lightning_storm_01_a", aliases: ["Amorce torrentielle", "Empower"] },
  { key: "stormcaller_lightning_storm_02_b", aliases: ["Orage foudroyant", "Lightning Storm"] },
  { key: "strafe", aliases: ["Invocation de carquois", "Summoning Quiver"] },
  { key: "strafe_a", aliases: ["Salve"] },
  { key: "strike_of_judgement_01", aliases: ["Frappe de jugement", "Dégager la brèche", "Clear the Breach"] },
  { key: "strong_constitution_01_a", aliases: ["Focus de corps", "Focus of Body"] },
  { key: "subduction", aliases: ["Subduction"] },
  { key: "summonskel5", aliases: ["Irradiation de Mort"] },
  { key: "summonskeleton1", aliases: ["Essence de Neddra", "Neddra's Essence"] },
  { key: "summonskeleton2", aliases: ["Chevalier squelettique inférieur"] },
  { key: "supportive_care", aliases: ["Soins de soutien"] },
  { key: "surge_a", aliases: ["Éléments déchaînés", "Raging Elements"] },
  { key: "surge_f", aliases: ["Tornade sauvage", "Savage Twister"] },
  { key: "surgical_strike", aliases: ["Frappe chirurgicale"] },
  { key: "surging_flames", aliases: ["Éruption", "Pluie d'étincelles", "Feu éclatant", "Eruption", "Flash Fire"] },
  { key: "survival2", aliases: ["Fugacité", "Elusiveness"] },
  { key: "sweep2", aliases: ["Coup final", "Final Blow"] },
  { key: "sweep3b", aliases: ["Frappe rapide"] },
  { key: "sweep3c", aliases: ["Frappe primitive"] },
  { key: "sweep4", aliases: ["Frappe féroce", "Fierce Strike"] },
  { key: "sweep4b", aliases: ["Coup puissant", "Mighty Blow"] },
  { key: "swiftstrike1a", aliases: ["Frappe téméraire", "Reckless Strike"] },
  { key: "swiftstrike2", aliases: ["Bond of Alacrity"] },
  { key: "swordsmith1", aliases: ["Frappe soudaine", "Sudden Strike"] },
  { key: "tactician_ablative_coil_a", aliases: ["Bobine ablative", "Ablative Coil"] },
  { key: "tactician_ablative_coil_b", aliases: ["Couplet d'occlusion"] },
  { key: "tactician_ablative_coil_c", aliases: ["Conductivité améliorée", "Enhanced Conductivity"] },
  { key: "tactician_barrier_augument_a", aliases: ["Effort de dernière minute", "Bouclier orageux", "Last Ditch Effort"] },
  { key: "tactician_barrier_augument_b", aliases: ["Barrière à distance", "Barrier Remote"] },
  { key: "tactician_curative_beam", aliases: ["Rayon curatif", "Curative Beam"] },
  { key: "tactician_curative_bolt", aliases: ["Curative Remote"] },
  { key: "tactician_curative_core_b", aliases: ["Noyau curatif", "Curative Core"] },
  { key: "tactician_curative_engine", aliases: ["Moteur curatif", "Curative Engine"] },
  { key: "tactician_curative_primer_a", aliases: ["Curative Blast"] },
  { key: "tactician_curative_torrent", aliases: ["Curative Torrent"] },
  { key: "tactician_curative_torrent_1", aliases: ["Émanation de Vie", "Emanate Life"] },
  { key: "tactician_devastative_augument", aliases: ["Combat à distance", "Battle Remote"] },
  { key: "tactician_devastative_augument_a", aliases: ["Odeur de sang", "Scent of Blood"] },
  { key: "tactician_empyrean_bolt", aliases: ["Empyrean Bolt"] },
  { key: "tactician_empyrean_engine", aliases: ["Machine empyréenne", "Empyrean Engine"] },
  { key: "tactician_empyrean_primer", aliases: ["Rayon empyréen", "Empyrean Ray"] },
  { key: "tactician_fortification_core", aliases: ["Noyau de Fortification", "Fortification Core"] },
  { key: "tactician_glacial_torrent", aliases: ["Pic à glace", "Glacial Torrent", "Glacial Spike", "Glacial Insignia"] },
  { key: "tactician_infernal_torrent", aliases: ["Infernal Torrent"] },
  { key: "tactician_infernal_torrent_a", aliases: ["Ardeur", "Scorch"] },
  { key: "tactician_mass_curative_engine_b", aliases: ["Moteur réparateur"] },
  { key: "tactician_mass_repulsion", aliases: ["Répulsion massive", "Mass Repulsion"] },
  { key: "tactician_necrotic_bolt", aliases: ["Necrotic Bolt"] },
  { key: "tactician_necrotic_core", aliases: ["Noyau nécrotique", "Fontis de courroux", "Font of Wrath"] },
  { key: "tactician_necrotic_core_b", aliases: ["Fontis de frénésie", "Font of Frenzy"] },
  { key: "tactician_necrotic_engine", aliases: ["Moteur nécrotique"] },
  { key: "tactician_necrotic_primer", aliases: ["Rayon nécrotique", "Chute de courroux", "Wrathfall"] },
  { key: "tactician_necrotic_torrent", aliases: ["Variation planaire"] },
  { key: "tempest_adrenalin_boost", aliases: ["Fontis de soif de sang", "Font of Bloodlust"] },
  { key: "tempest_bounce_shot_a", aliases: ["Destruction en chaîne", "Déroute", "Confound", "Chain Destruction"] },
  { key: "tempest_brace", aliases: ["Recul libre", "Free Recoil"] },
  { key: "tempest_close_training_a", aliases: ["Attitude défensive", "Entraînement au corps à corps", "Defensive Pose", "Close Training"] },
  { key: "tempest_close_training_z", aliases: ["Défense des déchus", "Defend the Fallen"] },
  { key: "tempest_difficult_target_z", aliases: ["Ace Shot"] },
  { key: "tempest_endgame", aliases: ["Altération énergétique", "Energy Alteration"] },
  { key: "tempest_endgame_a", aliases: ["Unknown"] },
  { key: "tempest_explosive_grenade_a", aliases: ["Grenade étourdissante", "Stun Grenade"] },
  { key: "tempest_focus_fire", aliases: ["Attaque de factionnaire"] },
  { key: "tempest_identified_weakness_b", aliases: ["Animalisme", "Animalism", "Focused Fire"] },
  { key: "tempest_physical_training_y", aliases: ["Unknown"] },
  { key: "tempest_physical_training_z", aliases: ["Nous sommes insoumis !"] },
  { key: "tempest_wellplacedshots", aliases: ["Moteur d'implosion", "Implosion Engine"] },
  { key: "track_humanoids_01_a", aliases: ["Instincts multiples", "Multiple Instincts"] },
  { key: "triage1", aliases: ["Médecin de guerre", "Battlefield Medic"] },
  { key: "triage3", aliases: ["Cure de jouvence"] },
  { key: "trinket20a", aliases: ["Conduit du pouvoir", "Conduit of Power"] },
  { key: "trinket4", aliases: ["Appel précoce", "Hasten Call", "Proper Timing"] },
  { key: "tumble1", aliases: ["Chevauchée du vent", "Enfilade", "Ride the Wind", "Thread the Trees"] },
  { key: "tumble1a", aliases: ["Déformation de l'ombre", "Shadow Warp"] },
  { key: "tumble1b", aliases: ["Retrait", "Withdrawal"] },
  { key: "twilight_force_01_b", aliases: ["Grâce à l'éther", "Force crépusculaire"] },
  { key: "twin_strike", aliases: ["Attaques complémentaires", "Soleil levant", "Follow Up Attacks", "Rising Sun"] },
  { key: "twin_strike_a", aliases: ["Moisson", "Lame fiévreuse", "Reaping Harvest", "Blade Rush"] },
  { key: "underwaterbreath1a", aliases: ["Appel des profondeurs", "Flux étrangleur", "Call of the Depths", "Choking Flood"] },
  { key: "underwaterbreath1b", aliases: ["Ablution"] },
  { key: "underwaterbreath1c", aliases: ["Revers de fortune", "Reversal of Fortune"] },
  { key: "untangle", aliases: ["Démêlage"] },
  { key: "untangle_b", aliases: ["Excès partagé", "Flux et reflux", "Rasement", "Multiple Oscillations", "Ebb and Flow", "Alternative Treatment", "Ground Zero"] },
  { key: "urgent_care", aliases: ["Soins d'urgence"] },
  { key: "venomoustrap1a", aliases: ["Épines de courroux"] },
  { key: "venomoustrap2a", aliases: ["Parasite"] },
  { key: "verse_of_fascination_a", aliases: ["Couplet captivant"] },
  { key: "verse_of_joy", aliases: ["Couplet de joie"] },
  { key: "verse_of_vitality", aliases: ["Couplet de vitalité"] },
  { key: "vex", aliases: ["Vexation"] },
  { key: "virtuoso_b", aliases: ["Impulsion distrayante", "Distracting Pulse"] },
  { key: "virtuous_conviction_01", aliases: ["Unknown"] },
  { key: "vitalizingshield1b", aliases: ["Bouclier de chêne", "Lifegiving Veil"] },
  { key: "vitalizingshield2", aliases: ["Lien d'âme", "Renouveau de la Terre", "Earthen Renewal"] },
  { key: "void_knight-improved_rift_summon", aliases: ["Gravity Void"] },
  { key: "void_knight-improved_rift_summon_a", aliases: ["Vortex glacé", "Rejeton planaire", "Icy Vortex", "Planar Spout"] },
  { key: "void_knight-insatiable_hunger_a", aliases: ["Chant purificateur", "Cleansing Chant"] },
  { key: "void_knight-pact_a", aliases: ["Contact de la faucheuse", "Contact des Ténèbres"] },
  { key: "void_knight-ravenous_strength_b", aliases: ["Accord de Puissance", "Accord of Power"] },
  { key: "void_knight-rift_summon", aliases: ["Corruption éthérée", "Rift Summon", "Ethereal Corruption"] },
  { key: "void_knight-rift_summon_a", aliases: ["Defile"] },
  { key: "void_knight-tempest", aliases: ["Unknown"] },
  { key: "void_knight-void_a", aliases: ["Unknown"] },
  { key: "void_knight_rift_reversal_a", aliases: ["Rayon infernal", "Infernal Beam"] },
  { key: "void_knight_rift_shield", aliases: ["Bouclier de Faille", "Rift Shield"] },
  { key: "void_knight_staggering_rage_b", aliases: ["Unknown"] },
  { key: "void_knight_staggering_rage_f_5", aliases: ["Réanimation suspendue", "Suspended Reanimation"] },
  { key: "void_knight_void_storm_a", aliases: ["Unknown"] },
  { key: "voidknight_catalyze_01_a", aliases: ["Bouclier malveillant", "Malevolent Shield"] },
  { key: "voidknight_ravenous_defence_01", aliases: ["Accord de Résistance", "Accord of Resilience"] },
  { key: "voidknight_ravenous_defence_01_a", aliases: ["Unknown"] },
  { key: "vortex", aliases: ["Tsunami"] },
  { key: "warchanter_battle_song", aliases: ["Chant de guerre", "Battlesong"] },
  { key: "warchanter_best_laid_plans", aliases: ["Les Meilleurs Projets", "Best Laid Plans"] },
  { key: "warchanter_bond_of_brotherhood", aliases: ["Lien de fraternité", "Bond of Brotherhood"] },
  { key: "warchanter_brush_it_off", aliases: ["Conduit de la Nature", "Conduit of Nature"] },
  { key: "warchanter_catch_breath", aliases: ["Catch Your Breath!"] },
  { key: "warchanter_dont_give_up", aliases: ["L'abandon n'est pas une option !", "Don't give up!"] },
  { key: "warchanter_encouraging_cries", aliases: ["Cris d'encouragement", "Encouraging Cries"] },
  { key: "warchanter_excellent_strike", aliases: ["Excellente frappe !", "Excellent Strike!"] },
  { key: "warchanter_get_in_there", aliases: ["Get in there!"] },
  { key: "warchanter_get_through", aliases: ["Nous y arriverons !"] },
  { key: "warchanter_nobody_backs_down", aliases: ["On ne lâche rien !", "Nobody Backs Down!"] },
  { key: "warchanter_phalanx", aliases: ["Phalanx!"] },
  { key: "warchanter_stand_and_deliver", aliases: ["Du cran et des coups !", "Stand and Deliver!"] },
  { key: "warchanter_stand_and_fight", aliases: ["Du cran et du courage !", "Stand and Fight!"] },
  { key: "warchanter_stand_tall", aliases: ["Gardez la tête haute !", "Stand Tall!"] },
  { key: "warchanter_survivors_slash", aliases: ["Blâme de la Nature", "Nature's Censure", "Survivor's Slash"] },
  { key: "warchanter_turn_the_tide", aliases: ["Décret de la Nature", "Nature's Edict"] },
  { key: "warchanter_united_we_stand", aliases: ["L'union fait la force !"] },
  { key: "warchanter_with_you", aliases: ["Je suis avec vous !", "I'm with you!"] },
  { key: "warchanter_wont_falter", aliases: ["Nous ne fléchirons point !"] },
  { key: "warchanter_your_shield", aliases: ["Je vous couvre !", "I'm your shield!"] },
  { key: "ward1z", aliases: ["Arresting Presence"] },
  { key: "ward1zz", aliases: ["Orbes du courant", "Explosion choquante", "Orbs of the Stream", "Cleansing Rush"] },
  { key: "ward3", aliases: ["Conflagration spirituelle"] },
  { key: "ward3b", aliases: ["Garde-Faille"] },
  { key: "ward4", aliases: ["Armure de pierre"] },
  { key: "warden-crushing_wave", aliases: ["Eaux rageuses", "Crushing Waves", "Raging Waters"] },
  { key: "warden-deluge", aliases: ["Dons élémentaires", "Elemental Gifts"] },
  { key: "warden-deluge_a", aliases: ["Avalanche"] },
  { key: "warden-dissolution_e", aliases: ["Zéphyr", "Voies convergentes", "Zephyr", "Paths Converge"] },
  { key: "warden-downpour", aliases: ["Pluie torrentielle", "Averse", "Downpour", "Cloudburst"] },
  { key: "warden-healing_cataract", aliases: ["Cataracte de soins", "Taillade glacée", "Healing Cataract", "Icy Cleave"] },
  { key: "warden-healing_cataract_a", aliases: ["Éther ondulant", "Rippling Ether"] },
  { key: "warden-healing_flood", aliases: ["Inondation de soins", "Healing Flood"] },
  { key: "warden-healing_flood_b", aliases: ["Inonder", "Inundate"] },
  { key: "warden-orbs_of_the_tide", aliases: ["Orbes du flux", "Orbs of the Tide"] },
  { key: "warden-overflow_b", aliases: ["Bienfait aqueux", "Aqueous Blessing"] },
  { key: "warden-tidal_surge", aliases: ["Unknown"] },
  { key: "warden-waterjet", aliases: ["Jet d'eau"] },
  { key: "warden-waterjet_a", aliases: ["Eaux apaisantes"] },
  { key: "warden-waterjet_b", aliases: ["Déluge", "Deluge"] },
  { key: "warlord-cutting_distraction_a", aliases: ["Bombardement de flammes", "Flame Blitz"] },
  { key: "warlord-killing_field", aliases: ["Déviation constante", "Abattoir", "Constant Deviation"] },
  { key: "warlord_deadly_posture", aliases: ["Deadly Posture"] },
  { key: "warlord_defensive_posture2_b", aliases: ["Posture défensive", "Defensive Posture"] },
  { key: "warlord_king_of_the_hill_a", aliases: ["Unknown"] },
  { key: "warlord_ready_posture", aliases: ["Unknown"] },
  { key: "warlord_recovery_posture", aliases: ["Posture de récupération", "Planar Rejuvenation"] },
  { key: "warlord_recovery_posture_a", aliases: ["Vitrification", "Vitrify"] },
  { key: "weakening_essence_01", aliases: ["Épieur silencieux", "Silent Stalker"] },
  { key: "weakening_essence_01_a_5", aliases: ["Dupliquombre", "Shadow Twin"] },
  { key: "weapon_barrage", aliases: ["Barrage d'armes", "Aiguille d'ombre", "Trait de perturbation", "Shadow Spire", "Disruption Bolt"] },
  { key: "whirlingblades1", aliases: ["Unknown"] },
  { key: "whirlingblades3", aliases: ["Déluge de coups", "Flurry"] },
  { key: "whirlwind1a", aliases: ["Frappe du maelström"] },
  { key: "whirlwind1b", aliases: ["Crue subite", "Flash Flood"] },
  { key: "whirlwind2", aliases: ["Bête acculée", "Cornered Beast"] },
  { key: "whirlwind4", aliases: ["Élémentaire d'Air mineur", "Rancid Cleave"] },
  { key: "whirlwind4i", aliases: ["Derviche tourbillonnant", "Whirling Dervish"] },
  { key: "world_event_griffon_pet_01", aliases: ["Appel : Griffon", "Appel : Griffon majeur", "Call: Greater Griffon", "Call: Griffon"] },
  { key: "auto_attack_1", aliases: ["Attaque auto.", "Équation ténébréenne"] },
  { key: "warlord-cracking_skulls_b", aliases: ["Action punitive"] },
];

export function normalizeAbilityName(s: string) {
  return (s ?? "")
    .toLowerCase()
    .trim()
    .replace(/\s+/g, " ")
    .replace(/[’'"]/g, "")
    .replace(/[^a-z0-9\s\-:]/g, "");
}

export function getAbilityIconKey(
  abilityName: string,
  rules: AbilityIconRule[] = ABILITY_ICON_RULES
): string | null {
  const target = normalizeAbilityName(abilityName);
  for (const rule of rules) {
    for (const a of rule.aliases) {
      if (normalizeAbilityName(a) === target) return rule.key;
    }
  }
  return null;
}

export function getAbilityIconUrl(key: string): string | null {
  const k = (key ?? "").trim();
  if (!k) return null;
  return `/abilities/${k}.jpg`;
}
